/**
 * exportStaleness.ts
 *
 * A tiny, pure guard for the "stale export" problem the dense-aerial cross-check
 * exposed: a report or product generated by an OLDER app version can carry
 * claims a newer version has since corrected (e.g. a drone scan mislabelled
 * "Terrestrial Laser Scan", or the loaded sample reported as the file total).
 * Both of those were fixed in v0.4.9 — but a PDF exported by v0.4.8 still says
 * the wrong thing forever.
 *
 * The honest fix is not to rewrite old files; it is to NOTICE when an artifact
 * was produced by an older build than the one now open, and tell the user the
 * current app would regenerate it differently. This module is the pure decision
 * core for that: compare the stamped producing-version against the running one.
 * No DOM, no app state — unit-tested in Node; a UI banner wires on top later.
 */

/**
 * Parse a dotted version ("0.5.2", "v0.5.2", "0.5") into numeric components.
 * A leading `v` is tolerated; non-numeric or missing parts read as 0, so a
 * malformed stamp degrades to a low version rather than throwing.
 */
export function parseVersion(version: string): readonly number[] {
  return version
    .trim()
    .replace(/^v/i, '')
    .split('.')
    .map((p) => {
      const n = parseInt(p, 10);
      return Number.isFinite(n) ? n : 0;
    });
}

/**
 * Compare two dotted versions. Returns -1 if `a` < `b`, 1 if `a` > `b`, 0 if
 * equal. Shorter versions are zero-padded ("0.5" === "0.5.0").
 */
export function compareVersions(a: string, b: string): -1 | 0 | 1 {
  const pa = parseVersion(a);
  const pb = parseVersion(b);
  const len = Math.max(pa.length, pb.length);
  for (let i = 0; i < len; i++) {
    const da = pa[i] ?? 0;
    const db = pb[i] ?? 0;
    if (da < db) return -1;
    if (da > db) return 1;
  }
  return 0;
}

/**
 * True when an artifact produced by `producedVersion` is older than the
 * `currentVersion` now running — i.e. a regenerate could differ. Empty or
 * unparseable `producedVersion` is treated as stale (we can't prove it's
 * current), so an unstamped legacy export is flagged rather than trusted.
 */
export function isExportStale(producedVersion: string | undefined | null, currentVersion: string): boolean {
  if (!producedVersion || producedVersion.trim() === '') return true;
  return compareVersions(producedVersion, currentVersion) < 0;
}

/**
 * A short, user-facing note when an export is stale, or `null` when it is
 * current (or newer). Names both versions so the user can decide whether to
 * regenerate. Deliberately does not claim WHAT changed — only that the current
 * build would produce it freshly.
 */
export function staleExportReason(
  producedVersion: string | undefined | null,
  currentVersion: string,
): string | null {
  if (!isExportStale(producedVersion, currentVersion)) return null;
  const made = producedVersion && producedVersion.trim() !== '' ? `v${parseVersion(producedVersion).join('.')}` : 'an earlier version';
  return `This was generated by ${made}; the current build (v${parseVersion(currentVersion).join('.')}) may grade or label it differently. Regenerate it to pick up later corrections.`;
}
