import { test, expect, type Page, type Download } from '@playwright/test';
import { readFileSync, statSync } from 'node:fs';
import {
  dropTerrainAccessUtmLas, firePaletteAction, openAnalysePage, openAnalysePanel, openToolPage, showWorkspaceMode,
  type MeasureTestApi,
} from './helpers';
import { isBenignPageError } from './pageErrors';

/**
 * Golden journey: the main user path through the real UI, end to end, on the
 * licensed `terrain-access-utm.las` fixture (30×30 grid, UTM 13N; generated by
 * scripts/gen-terrain-access-fixture.ts). Each step waits on a real signal —
 * no fixed sleeps — and the whole journey must raise zero page errors and zero
 * console errors.
 *
 * The soak variant (@soak, own project, `npm run test:e2e:soak`) repeats
 * open → analyse → close and checks the JS heap and the displayed point count
 * return to baseline. Bound and measured runs are documented at SOAK_HEAP_BOUND.
 */

const WIDE = { width: 1440, height: 900 };

interface ErrorLog { errors: string[] }

function collectErrors(page: Page): ErrorLog {
  const log: ErrorLog = { errors: [] };
  page.on('pageerror', (err) => {
    if (!isBenignPageError(err.message)) log.errors.push(`pageerror: ${err.message}`);
  });
  page.on('console', (msg) => {
    if (msg.type() === 'error') log.errors.push(`console.error: ${msg.text()}`);
  });
  return log;
}

async function openFixture(page: Page): Promise<void> {
  await dropTerrainAccessUtmLas(page);
  await expect(page.locator('.olv-empty')).toBeHidden({ timeout: 20_000 });
  await expect(page.locator('.olv-layer')).toHaveCount(1);
  await expect(page.locator('.olv-dock .olv-tool', { hasText: /^Analyse$/ })).toBeEnabled({ timeout: 20_000 });
}

async function testApi(page: Page): Promise<void> {
  await page.waitForFunction(() => '__OLV_TEST_API__' in window, undefined, { timeout: 20_000 });
}

async function runAnalysis(page: Page): Promise<void> {
  await openAnalysePanel(page);
  await page.locator('.olv-analyse-run').click();
  await expect(page.locator('.olv-analyse-readiness .olv-analyse-ready:not(.is-skeleton)')).toHaveCount(3, {
    timeout: 30_000,
  });
}

async function closeScan(page: Page): Promise<void> {
  await page.locator('.olv-tool-close').click();
  await expect(page.locator('.olv-empty')).toBeVisible({ timeout: 20_000 });
  await expect(page.locator('.olv-layer')).toHaveCount(0);
}

async function expectNonEmptyDownload(download: Download, name: RegExp): Promise<string> {
  expect(download.suggestedFilename()).toMatch(name);
  const path = await download.path();
  if (!path) throw new Error('download produced no local path');
  expect(statSync(path).size).toBeGreaterThan(0);
  return path;
}

const CANDIDATE_POINTS = [
  { x: 0.5, y: 0.5 }, { x: 0.46, y: 0.46 }, { x: 0.54, y: 0.54 },
  { x: 0.5, y: 0.42 }, { x: 0.5, y: 0.58 }, { x: 0.42, y: 0.5 }, { x: 0.58, y: 0.5 },
];

/** Annotate by a real canvas click: a miss leaves no editor open, so try a few
 * points near the centre of the framed grid until the editor appears. */
async function placeAnnotation(page: Page, title: string): Promise<void> {
  const box = await page.locator('canvas').first().boundingBox();
  if (!box) throw new Error('scene canvas has no bounding box');
  const editor = page.locator('.olv-anno-editor');
  let opened = false;
  for (const p of CANDIDATE_POINTS) {
    await page.mouse.click(box.x + box.width * p.x, box.y + box.height * p.y);
    try {
      await expect(editor).toBeVisible({ timeout: 2_000 });
      opened = true;
      break;
    } catch {
      // missed the cloud; next candidate
    }
  }
  if (!opened) throw new Error('no candidate canvas point opened the annotation editor');
  await page.locator('.olv-anno-editor-title').fill(title);
  await page.locator('.olv-anno-editor-save').click();
  await expect(editor).toBeHidden();
}

function annotationRow(page: Page, title: string) {
  return page.locator('.olv-anno-panel .olv-ap-row').filter({ has: page.locator('.olv-ap-name', { hasText: title }) });
}

test.describe('golden journey', () => {
  test('open → frame → colour → measure → annotate → analyse → contours → export → session round-trip → close', async ({ page }) => {
    test.slow();
    const log = collectErrors(page);
    await page.setViewportSize(WIDE);
    await page.goto('/?test=1');
    await expect(page.locator('.olv-empty')).toBeVisible();

    // OPEN
    await openFixture(page);
    await testApi(page);

    // FRAME
    const frame = page.locator('.olv-tool', { hasText: 'Frame' });
    await expect(frame).toBeEnabled();
    await frame.click();

    // COLOUR MODES: every mode the LAS carries is selectable and takes effect.
    for (const mode of ['Height', 'Intensity', 'Classification', 'Height']) {
      const chip = page.locator('.olv-chip', { hasText: new RegExp(`^${mode}$`) }).first();
      if (mode !== 'Height' && (await chip.count()) === 0) continue;
      await chip.click();
      await expect(chip).toHaveClass(/olv-chip-active/);
    }

    // MEASURE: a distance and an area.
    await page.locator('.olv-tool', { hasText: 'Measure' }).click();
    await expect(page.locator('.olv-measure-bar')).toBeVisible();
    await page.evaluate(() => {
      const api = (window as unknown as { __OLV_TEST_API__: MeasureTestApi }).__OLV_TEST_API__;
      api.setMeasureKind('distance');
      api.placeMeasurementPoint({ x: 0, y: 0, z: 0 });
      api.placeMeasurementPoint({ x: 3, y: 4, z: 0 });
      api.setMeasureKind('area');
      api.placeMeasurementPoint({ x: 0, y: 0, z: 0 });
      api.placeMeasurementPoint({ x: 2, y: 0, z: 0 });
      api.placeMeasurementPoint({ x: 2, y: 2, z: 0 });
      api.placeMeasurementPoint({ x: 0, y: 2, z: 0 });
      api.finishMeasurement?.();
    });
    await showWorkspaceMode(page, 'work');
    await expect(page.locator('.olv-mp-row')).toHaveCount(2, { timeout: 5_000 });
    await expect(page.locator('.olv-mp-row').first()).toContainText(/5(\.0+)?\s*m/);
    await page.locator('.olv-tool', { hasText: 'Measure' }).click(); // leave Measure
    await expect(page.locator('.olv-measure-bar')).toBeHidden();

    // ANNOTATE
    await page.locator('.olv-tool', { hasText: 'Annotate' }).click();
    await showWorkspaceMode(page, 'work');
    await placeAnnotation(page, 'Golden journey note');
    await expect(annotationRow(page, 'Golden journey note')).toHaveCount(1);
    await page.locator('.olv-tool', { hasText: 'Annotate' }).click(); // leave Annotate

    // TERRAIN ANALYSIS + CONTOURS: the run draws contours as a derived layer.
    await runAnalysis(page);
    const derivedList = page.locator('.olv-analyse-layer-controls', { hasText: 'Derived layers' });
    await expect(derivedList).not.toHaveClass(/olv-hidden/, { timeout: 20_000 });
    await openAnalysePage(page, 'contours');
    await expect(page.locator('.olv-analyse-layer-controls', { hasText: /Contours/ }).first()).toBeVisible();

    // DATASET STORY reflects the loaded scan.
    await firePaletteAction(page, 'Dataset Story', 'Dataset Story');
    const card = page.locator('.olv-modal .olv-story-card');
    await expect(card).toBeVisible();
    await expect(card).toContainText('Primary limiter');
    await page.keyboard.press('Escape');
    await expect(card).toBeHidden();

    // EXPORT: convert the cloud to XYZ and capture the download.
    await showWorkspaceMode(page, 'output');
    const exportPanel = page.locator('.olv-export-panel');
    await expect(exportPanel).toBeVisible({ timeout: 20_000 });
    if (await exportPanel.evaluate((el) => el.classList.contains('olv-collapsed'))) {
      await exportPanel.locator('.olv-panel-head').click();
    }
    await exportPanel.locator('.olv-bc-pill', { hasText: 'XYZ' }).click();
    const [xyz] = await Promise.all([page.waitForEvent('download'), exportPanel.locator('.olv-bc-convert').click()]);
    const xyzPath = await expectNonEmptyDownload(xyz, /^terrain-access-utm.*\.xyz$/);
    const xyzLines = readFileSync(xyzPath, 'utf8').trim().split('\n');
    expect(xyzLines.length).toBeGreaterThanOrEqual(900);

    // SAVE SESSION
    await openToolPage(page, 'Measure');
    const [session] = await Promise.all([
      page.waitForEvent('download'),
      page.locator('.olv-mp-action', { hasText: 'Export' }).click(),
    ]);
    const sessionPath = await expectNonEmptyDownload(session, /^terrain-access-utm.*\.olvsession$/);
    const sessionText = readFileSync(sessionPath, 'utf8');
    expect(sessionText).toContain('Golden journey note');

    // RELOAD → reopen the scan → IMPORT SESSION
    await page.reload();
    await expect(page.locator('.olv-empty')).toBeVisible();
    await openFixture(page);
    await showWorkspaceMode(page, 'work');
    await expect(page.locator('.olv-mp-row')).toHaveCount(0);
    const dt = await page.evaluateHandle((t) => {
      const d = new DataTransfer();
      d.items.add(new File([t], 'terrain-access-utm.olvsession'));
      return d;
    }, sessionText);
    await page.dispatchEvent('body', 'drop', { dataTransfer: dt });

    // RESTORED
    await expect(page.locator('.olv-mp-row')).toHaveCount(2, { timeout: 10_000 });
    await expect(page.locator('.olv-mp-row').first()).toContainText(/5(\.0+)?\s*m/);
    await expect(annotationRow(page, 'Golden journey note')).toHaveCount(1);

    // CLOSE
    await closeScan(page);

    expect(log.errors, log.errors.join('\n')).toEqual([]);
  });
});

/**
 * Soak: repeat open → analyse → close N times (OLV_SOAK_CYCLES, default 10).
 *
 * Heap is read after a forced GC (Chromium CDP) — performance.memory is
 * Chromium-only, so other engines skip the heap check and keep the point-count
 * check. SOAK_HEAP_BOUND is the allowed growth of the post-close heap over the
 * post-close heap of cycle 1 (the first cycle pays one-off lazy-chunk and cache
 * costs, so it, not the pre-open page, is the baseline).
 *
 * Measured 2026-09-25, 10 cycles, Chromium, macOS, 3 runs: post-close heap
 * 13.64 MB on every cycle of every run (growth 0.00 MB), displayed points
 * 900 open / 0 closed. Growth was nil, so the bound is a fixed 2 MB allowance
 * for GC and lazy-chunk noise on other machines, not a multiple of it.
 */
const SOAK_CYCLES = Number(process.env.OLV_SOAK_CYCLES ?? 10);
const SOAK_HEAP_BOUND = 2 * 1024 * 1024;

async function shownPoints(page: Page): Promise<number> {
  const text = (await page.locator('.olv-debug').textContent()) ?? '';
  const m = /points\s+([\d,  ]+)\s+shown/.exec(text);
  return m ? Number(m[1].replace(/[^\d]/g, '')) : 0;
}

test.describe('golden journey soak @soak', () => {
  test('open → analyse → close repeated returns heap and resident points to baseline', async ({ page, browserName }) => {
    test.setTimeout(60_000 + SOAK_CYCLES * 30_000);
    const log = collectErrors(page);
    await page.setViewportSize(WIDE);
    await page.goto('/?test=1&debug=1');
    await expect(page.locator('.olv-empty')).toBeVisible();

    const cdp = browserName === 'chromium' ? await page.context().newCDPSession(page) : null;
    const heap = async (): Promise<number | null> => {
      if (!cdp) return null;
      await cdp.send('HeapProfiler.collectGarbage');
      await cdp.send('HeapProfiler.collectGarbage');
      return page.evaluate(() => (performance as unknown as { memory?: { usedJSHeapSize: number } }).memory?.usedJSHeapSize ?? null);
    };

    const heaps: (number | null)[] = [];
    const points: number[] = [];
    let peakPoints = 0;
    for (let i = 0; i < SOAK_CYCLES; i++) {
      await openFixture(page);
      await expect.poll(() => shownPoints(page), { timeout: 20_000 }).toBeGreaterThan(0);
      peakPoints = Math.max(peakPoints, await shownPoints(page));
      await runAnalysis(page);
      await closeScan(page);
      await expect.poll(() => shownPoints(page), { timeout: 20_000 }).toBe(0);
      points.push(await shownPoints(page));
      heaps.push(await heap());
    }

    const base = heaps[0];
    const growth = heaps.map((h) => (h === null || base === null ? null : h - base));
    const mb = (b: number | null) => (b === null ? 'n/a' : (b / 1048576).toFixed(2));
    const report = `soak ${browserName} cycles=${SOAK_CYCLES} peakPoints=${peakPoints} ` +
      `heapMB=[${heaps.map(mb).join(', ')}] growthMB=[${growth.map(mb).join(', ')}] points=[${points.join(', ')}]`;
    console.log(report);
    test.info().annotations.push({ type: 'soak', description: report });

    expect(points.every((p) => p === 0)).toBe(true);
    const worst = Math.max(...growth.map((g) => g ?? 0));
    expect(worst, report).toBeLessThanOrEqual(SOAK_HEAP_BOUND);
    expect(log.errors, log.errors.join('\n')).toEqual([]);
  });
});
