import { test, expect, type Page } from '@playwright/test';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { showWorkspaceMode, suppressOnboardingTour } from './helpers';

/**
 * lasEvlrCrs.spec.ts
 *
 * A LAS 1.4 file whose coordinate system is stored ONLY in an extended VLR
 * after the point data (`tests/fixtures/evlr-crs-utm15.{las,laz}`, generated by
 * `scripts/gen-evlr-crs-fixture.ts`). The Inspector must name the compound
 * CRS, and the Export readiness must not raise a coordinate-system condition.
 */

async function dropFixture(page: Page, name: string): Promise<void> {
  const bytes = readFileSync(fileURLToPath(new URL(`../fixtures/${name}`, import.meta.url)));
  const dataTransfer = await page.evaluateHandle(
    ([b, n]) => {
      const dt = new DataTransfer();
      dt.items.add(new File([new Uint8Array(b as number[])], n as string));
      return dt;
    },
    [[...bytes], name] as const,
  );
  await page.dispatchEvent('body', 'drop', { dataTransfer });
}

for (const name of ['evlr-crs-utm15.las', 'evlr-crs-utm15.laz']) {
  test(`${name}: the EVLR-only CRS reaches the Inspector and Export readiness`, async ({ page }) => {
    await suppressOnboardingTour(page);
    await page.goto('/');
    await expect(page.locator('.olv-empty')).toBeVisible();
    await dropFixture(page, name);
    await expect(page.locator('.olv-empty')).toBeHidden({ timeout: 20_000 });

    await page.locator('summary', { hasText: 'Coordinate system' }).first().click();
    const crs = page.locator('.olv-crs-summary').first();
    await expect(crs).toBeVisible({ timeout: 15_000 });
    await expect(page.locator('.olv-crs-name').first()).toContainText('UTM zone 15N');
    await expect(page.locator('.olv-crs-epsg').first()).toHaveText('EPSG:6344');

    await showWorkspaceMode(page, 'output');
    const panel = page.locator('.olv-export-panel');
    await expect(panel).toBeVisible({ timeout: 20_000 });
    if (await panel.evaluate((el) => el.classList.contains('olv-collapsed'))) {
      await panel.locator('.olv-panel-head').click();
    }
    const health = panel.locator('.olv-health');
    await expect(health).toBeVisible({ timeout: 15_000 });
    const row = (label: string) => health.locator('.olv-health-row', { hasText: label });
    await expect(row('Coordinate system')).toContainText('Known');
    await expect(row('Vertical datum')).toContainText('Known');
    await expect(row('Coordinate system')).toHaveClass(/is-good/);
    await expect(row('Vertical datum')).toHaveClass(/is-good/);
  });
}
