/**
 * classifierGroundRecallDiagnosis.test.ts — the mechanisms behind the corpus's
 * two ground-recall collapses, asserted rather than asserted about.
 *
 * `validation/classifier-corpus/results-classifier-corpus.json` records that
 * ground recall is 1.00 on planar scenes, 0.64 on the 30 % ridge, 0.40 on
 * rolling terrain, and was 0.00 on the low-outlier scene before v2. Those are
 * measurements. This file holds the EXPLANATIONS, written as tests, so a wrong
 * explanation fails instead of sitting in a document.
 *
 * Two mechanisms, and they are not the same fault.
 *
 *   1. LOW OUTLIERS. Grayscale opening removes peaks and not pits, so a
 *      below-ground return is never carved out by the morphology: it seeds the
 *      minimum grid, the erosion carries it across the whole structuring
 *      element, and once blunders are closer together than the largest window
 *      every cell's erosion window holds one, so the opened surface collapses
 *      to blunder level everywhere. Fixed in v2 by rejecting the outlier before
 *      the grid minimum.
 *
 *   2. CURVED AND STEEP TERRAIN. The cut fires when a cell stands more than
 *      `elevThresholdM + slope × run` above the opened surface. That is a
 *      LINEAR bound on how far terrain may fall over a run. Real terrain with
 *      curvature does not fall linearly: on the corpus's rolling scene the drop
 *      over one cell is already 1.28 m against a 0.45 m allowance, and it
 *      saturates near 6.2 m while the allowance keeps growing at 0.15 m per
 *      cell. No single slope constant fits both scales. This is a
 *      parameter-to-terrain mismatch with a real trade against carving out
 *      buildings, and NOTHING here tunes a default to hide it.
 *
 * The scenes are synthetic and generated by this project. They show where the
 * rules break; they are not field validation.
 */
import { describe, it, expect } from 'vitest';
import {
  buildCorpus,
  scaleLengthParams,
  scoreScene,
  TRUTH_GROUND,
  TRUTH_LOW_NOISE,
  type CorpusScene,
} from '../src/validation/classifierCorpus';
import {
  deriveClassification,
  CLASSIFIER_PRESET,
  type DeriveClassificationOptions,
} from '../src/render/class/deriveClassification';

const SCENES = buildCorpus();
const scene = (id: string): CorpusScene => SCENES.find((s) => s.id === id)!;

/** The options the corpus record is produced with. */
function optionsFor(s: CorpusScene): DeriveClassificationOptions {
  return {
    cellSizeM: s.cellSize,
    ...scaleLengthParams(CLASSIFIER_PRESET.params, s),
    ...(s.colors ? { colors: s.colors } : {}),
    ...(s.returnNumber && s.returnCount
      ? { returnNumber: s.returnNumber, returnCount: s.returnCount }
      : {}),
  };
}

/** Ground recall of a run, optionally over a truncated prefix of the scene. */
function groundRecall(
  s: CorpusScene,
  extra: Partial<DeriveClassificationOptions> = {},
  points = s.count,
): number {
  const positions = points === s.count ? s.positions : s.positions.slice(0, points * 3);
  const truth = points === s.count ? s.truth : s.truth.slice(0, points);
  const result = deriveClassification(positions, points, { ...optionsFor(s), ...extra });
  const score = scoreScene(s.id, truth, result.codes);
  return score.byClass.find((m) => m.code === TRUTH_GROUND)!.recall ?? NaN;
}

/** The published ladder of window radii, in cells, and the threshold at each. */
function ladder(cellSize: number): { radiusCells: number; runM: number; allowance: number }[] {
  const p = CLASSIFIER_PRESET.params;
  const maxRadius = Math.max(1, Math.round(p.maxObjectSizeM / cellSize));
  const out: { radiusCells: number; runM: number; allowance: number }[] = [];
  for (let r = 1; r <= maxRadius; r *= 2) {
    out.push({
      radiusCells: r,
      runM: r * cellSize,
      allowance: p.elevThresholdM + p.slope * (r * cellSize),
    });
  }
  return out;
}

/**
 * The largest drop the scene's OWN bare earth makes across a Chebyshev window of
 * `radiusCells`, measured from the truth-labelled ground returns gridded at the
 * run cell size. This is what the morphological erosion sees.
 */
function terrainDrop(s: CorpusScene, radiusCells: number): number {
  const cell = s.cellSize;
  let minX = Infinity;
  let minY = Infinity;
  let maxX = -Infinity;
  let maxY = -Infinity;
  for (let i = 0; i < s.count; i++) {
    const x = s.positions[i * 3];
    const y = s.positions[i * 3 + 1];
    if (x < minX) minX = x;
    if (x > maxX) maxX = x;
    if (y < minY) minY = y;
    if (y > maxY) maxY = y;
  }
  const W = Math.ceil((maxX - minX) / cell) + 1;
  const H = Math.ceil((maxY - minY) / cell) + 1;
  const grid = new Float64Array(W * H).fill(NaN);
  for (let i = 0; i < s.count; i++) {
    if (s.truth[i] !== TRUTH_GROUND) continue;
    const cx = Math.min(W - 1, Math.floor((s.positions[i * 3] - minX) / cell));
    const cy = Math.min(H - 1, Math.floor((s.positions[i * 3 + 1] - minY) / cell));
    const c = cy * W + cx;
    const z = s.positions[i * 3 + 2];
    if (!Number.isFinite(grid[c]) || z < grid[c]) grid[c] = z;
  }
  let worst = 0;
  for (let y = 0; y < H; y++) {
    for (let x = 0; x < W; x++) {
      const here = grid[y * W + x];
      if (!Number.isFinite(here)) continue;
      let lowest = Infinity;
      for (let dy = -radiusCells; dy <= radiusCells; dy++) {
        for (let dx = -radiusCells; dx <= radiusCells; dx++) {
          const xx = x + dx;
          const yy = y + dy;
          if (xx < 0 || xx >= W || yy < 0 || yy >= H) continue;
          const v = grid[yy * W + xx];
          if (Number.isFinite(v) && v < lowest) lowest = v;
        }
      }
      if (lowest < Infinity && here - lowest > worst) worst = here - lowest;
    }
  }
  return worst;
}

describe('why the low-outlier scene collapsed', () => {
  const s = scene('low-outliers');
  /** The generator appends the thirty blunders last, so a prefix drops them. */
  const WITHOUT_BLUNDERS = s.count - 30;

  it('the blunders are the whole cause: removing them restores full recall', () => {
    // Same points, same parameters, same rules. Only the thirty gross returns
    // differ, so nothing else can be carrying the collapse.
    expect(groundRecall(s, { despikeNeighbourFactor: 0 })).toBe(0);
    expect(groundRecall(s, { despikeNeighbourFactor: 0 }, WITHOUT_BLUNDERS)).toBe(1);
  });

  it('damage is local at one blunder and total at thirty', () => {
    // A lone pit poisons its own cell and the cells whose bilinear DTM patch
    // touches it. Thirty of them across a forty-metre scene put a pit inside
    // every erosion window, and the opened surface drops everywhere.
    const one = groundRecall(s, { despikeNeighbourFactor: 0 }, WITHOUT_BLUNDERS + 1);
    const five = groundRecall(s, { despikeNeighbourFactor: 0 }, WITHOUT_BLUNDERS + 5);
    const thirty = groundRecall(s, { despikeNeighbourFactor: 0 });
    expect(one).toBeGreaterThan(0.97);
    expect(five).toBeLessThan(one);
    expect(thirty).toBe(0);
  });

  it('the drop only cuts because it exceeds the largest ladder allowance', () => {
    // The blunders are four metres deep. The published ladder tops out below
    // that, so the cut fires at every step; raising the base threshold past the
    // blunder depth stops it, which is the criterion and not a coincidence.
    const allowances = ladder(s.cellSize).map((step) => step.allowance);
    expect(Math.max(...allowances)).toBeLessThan(4);
    expect(groundRecall(s, { despikeNeighbourFactor: 0, elevThresholdM: 5 })).toBeGreaterThan(0.9);
  });

  it('v2 rejects the outlier before the grid minimum and recovers the ground', () => {
    expect(groundRecall(s, { despikeNeighbourFactor: 0 })).toBe(0);
    expect(groundRecall(s)).toBe(1);
    expect(CLASSIFIER_PRESET.params.despikeNeighbourFactor).toBeGreaterThan(0);
  });

  it('the blunders themselves are still called ground, and that is not fixed', () => {
    // Height above ground is clamped at zero, so a return below the surface
    // lands in the ground band. v2 stops a blunder from dragging the surface;
    // it does not give the classifier a noise class to put the blunder in.
    const result = deriveClassification(s.positions, s.count, optionsFor(s));
    const score = scoreScene(s.id, s.truth, result.codes);
    expect(score.lowNoisePoints).toBe(30);
    expect(score.lowNoiseCalledGround).toBe(30);
  });

  it('rejecting an outlier is reported, never silent', () => {
    const result = deriveClassification(s.positions, s.count, optionsFor(s));
    expect(result.warnings.some((w) => w.includes('low outlier'))).toBe(true);
  });
});

describe('why curved and steep terrain lose ground', () => {
  it('the allowance is linear in the window run while the terrain drop is not', () => {
    // Rolling terrain: the drop already exceeds the allowance at one cell, and
    // it saturates near twice the amplitude while the allowance keeps growing.
    const rolling = scene('rolling-terrain');
    for (const step of ladder(rolling.cellSize)) {
      expect(terrainDrop(rolling, step.radiusCells)).toBeGreaterThan(step.allowance);
    }
    // The saturation is the part a slope constant cannot express: the drop rises
    // by less than a metre between the two largest windows while the allowance
    // rises by more than a metre.
    const steps = ladder(rolling.cellSize);
    const last = steps[steps.length - 1];
    const previous = steps[steps.length - 2];
    expect(terrainDrop(rolling, last.radiusCells) - terrainDrop(rolling, previous.radiusCells))
      .toBeLessThan(last.allowance - previous.allowance);
  });

  it('a planar scene never crosses the allowance, which is why it scores 1.00', () => {
    const flat = scene('aerial-urban');
    for (const step of ladder(flat.cellSize)) {
      expect(terrainDrop(flat, step.radiusCells)).toBeLessThan(step.allowance);
    }
    expect(groundRecall(flat)).toBe(1);
  });

  it('the ridge crosses it from the first step, at twice the tolerated slope', () => {
    // The flanks fall at 30 % and the tolerance encodes 15 %.
    const ridge = scene('steep-terrain');
    const first = ladder(ridge.cellSize)[0];
    expect(terrainDrop(ridge, first.radiusCells)).toBeGreaterThan(first.allowance);
    expect(groundRecall(ridge)).toBeLessThan(0.7);
  });

  it('the grid cell is not the cause; the window run is', () => {
    // Quartering the cell barely moves rolling recall, because the ladder is
    // expressed in metres of object size and covers the same ground either way.
    // Shortening the ladder moves it a lot — which is the trade, not a fix: a
    // two-metre window no longer carves out a building.
    const rolling = scene('rolling-terrain');
    const fine = groundRecall(rolling, { cellSizeM: 0.5 });
    const coarse = groundRecall(rolling, { cellSizeM: 2 });
    expect(fine).toBeLessThan(0.5);
    expect(coarse).toBeLessThan(0.5);
    expect(groundRecall(rolling, { maxObjectSizeM: 2 })).toBeGreaterThan(0.85);
  });

  it('matching the slope parameter to the terrain recovers the ridge', () => {
    // Evidence for the recommended experiment, not a change to any default:
    // the ridge falls at 30 %, and a 30 % tolerance recovers all of it. Doing
    // this by default would loosen the tolerance everywhere and admit low
    // objects as ground, which this corpus does not measure.
    const ridge = scene('steep-terrain');
    expect(groundRecall(ridge, { slope: 0.3 })).toBe(1);
    expect(groundRecall(ridge)).toBeLessThan(0.7);
  });
});

describe('what the diagnosis does not claim', () => {
  it('leaves rolling terrain unfixed, and the published metric says so', () => {
    // v2 moved rolling ground recall by less than two points. The corpus record
    // keeps the low figure rather than a tuned one.
    const rolling = scene('rolling-terrain');
    const before = groundRecall(rolling, { despikeNeighbourFactor: 0 });
    const after = groundRecall(rolling);
    expect(after - before).toBeLessThan(0.02);
    expect(after).toBeLessThan(0.45);
  });

  it('the corpus keeps a class the classifier cannot emit, so the gap stays visible', () => {
    expect(TRUTH_LOW_NOISE).toBe(7);
    const s = scene('low-outliers');
    const result = deriveClassification(s.positions, s.count, optionsFor(s));
    expect(Array.from(result.codes)).not.toContain(TRUTH_LOW_NOISE);
  });
});
