/**
 * ept.test.ts — v0.3.3 — Entwine Point Tile (EPT) integration tests.
 *
 * Three layers covered:
 *   1. URL detection — recognise an EPT entrypoint URL.
 *   2. Manifest parsing — full validation of the ept.json shape, including
 *      the failure paths (malformed JSON, missing fields, unsupported
 *      version / dataType / hierarchyType, broken schema, broken bounds).
 *   3. Hierarchy parsing + octree traversal — partition entries into
 *      nodes vs links, walk child keys, round-trip address strings.
 *   4. URL construction — base / hierarchy / tile URL builders.
 *   5. Synthetic fixture round-trip — load the generated tests/fixtures/
 *      ept-tiny dataset, verify the manifest + hierarchy + tile sizes
 *      match what `make-ept-fixture.py` wrote.
 *
 * Pure Node — no DOM, no three.js, no network. The fixture lives in
 * tests/fixtures/ept-tiny/ and is generated by scripts/make-ept-fixture.py;
 * re-running the script with the default seed produces byte-identical
 * output, so this test is reproducible without checking the fixture into
 * git.
 */

import { readFileSync, statSync } from 'node:fs';
import { join } from 'node:path';
import { test, expect } from 'vitest';
import { detectEptUrl, parseEptMetadata } from '../src/io/ept/eptDetect';
import {
  parseHierarchyFile,
  partitionHierarchyMap,
  eptChildKeys,
} from '../src/io/ept/eptHierarchy';
import {
  eptBaseUrl,
  eptHierarchyUrl,
  eptRootHierarchyUrl,
  eptTileUrl,
  tileExtensionFor,
} from '../src/io/ept/eptUrls';
import {
  eptKeyToString,
  eptStringToKey,
} from '../src/io/ept/eptTypes';

const FIXTURE_DIR = join(__dirname, 'fixtures', 'ept-tiny');

// ─────────────────────────────────────────────────────────────────────────────
// URL detection
// ─────────────────────────────────────────────────────────────────────────────

test('detectEptUrl recognises canonical ept.json URLs', () => {
  expect(detectEptUrl('https://server/path/ept.json')).toBe(true);
  expect(detectEptUrl('https://server/path/ept.json?token=abc')).toBe(true);
  expect(detectEptUrl('https://server/EPT.json')).toBe(true); // case-insensitive
  expect(detectEptUrl('/local/path/ept.json')).toBe(true);
});

test('detectEptUrl rejects non-EPT URLs cleanly', () => {
  expect(detectEptUrl('https://server/path/cloud.laz')).toBe(false);
  expect(detectEptUrl('https://server/path/cloud.copc.laz')).toBe(false);
  expect(detectEptUrl('https://server/path/')).toBe(false);
  expect(detectEptUrl('https://server/ept.json.bak')).toBe(false);
});

// ─────────────────────────────────────────────────────────────────────────────
// Manifest parsing — happy path against the synthetic fixture
// ─────────────────────────────────────────────────────────────────────────────

test('parseEptMetadata parses the synthetic fixture cleanly', () => {
  const text = readFileSync(join(FIXTURE_DIR, 'ept.json'), 'utf8');
  const result = parseEptMetadata(text);
  expect(result.isEpt).toBe(true);
  if (!result.isEpt) return;
  expect(result.metadata.version).toMatch(/^1\./);
  expect(result.metadata.dataType).toBe('binary');
  expect(result.metadata.hierarchyType).toBe('json');
  expect(result.metadata.points).toBe(100);
  expect(result.metadata.span).toBe(128);
  // Schema must include X/Y/Z + intensity + classification.
  const names = result.metadata.schema.map((f) => f.name);
  expect(names).toContain('X');
  expect(names).toContain('Y');
  expect(names).toContain('Z');
  expect(names).toContain('Intensity');
  expect(names).toContain('Classification');
  // Bounds — both cube and conforming present, identical for the fixture.
  expect(result.metadata.bounds.cubic[0]).toBe(500_000);
  expect(result.metadata.bounds.conforming[0]).toBe(500_000);
  // SRS — the fixture carries UTM 12N WKT.
  expect(result.metadata.srs).toContain('UTM zone 12N');
});

// ─────────────────────────────────────────────────────────────────────────────
// Manifest parsing — failure paths
// ─────────────────────────────────────────────────────────────────────────────

test('parseEptMetadata rejects invalid JSON', () => {
  const result = parseEptMetadata('not json');
  expect(result.isEpt).toBe(false);
  if (result.isEpt) return;
  expect(result.reason).toMatch(/JSON/i);
});

test('parseEptMetadata rejects an unsupported version', () => {
  const minimal = JSON.stringify({
    version: '2.0.0',
    dataType: 'binary',
    hierarchyType: 'json',
    points: 0,
    span: 128,
    schema: [],
    bounds: [0, 0, 0, 1, 1, 1],
  });
  const result = parseEptMetadata(minimal);
  expect(result.isEpt).toBe(false);
  if (result.isEpt) return;
  expect(result.reason).toMatch(/version/i);
});

test('parseEptMetadata rejects an unsupported dataType', () => {
  const minimal = JSON.stringify({
    version: '1.1.0',
    dataType: 'parquet',
    hierarchyType: 'json',
    points: 0,
    span: 128,
    schema: [{ name: 'X', size: 4, type: 'signed' }, { name: 'Y', size: 4, type: 'signed' }, { name: 'Z', size: 4, type: 'signed' }],
    bounds: [0, 0, 0, 1, 1, 1],
  });
  const result = parseEptMetadata(minimal);
  expect(result.isEpt).toBe(false);
  if (result.isEpt) return;
  expect(result.reason).toMatch(/dataType/);
});

test('parseEptMetadata rejects a schema missing X/Y/Z', () => {
  const minimal = JSON.stringify({
    version: '1.1.0',
    dataType: 'binary',
    hierarchyType: 'json',
    points: 0,
    span: 128,
    schema: [{ name: 'Intensity', size: 2, type: 'unsigned' }],
    bounds: [0, 0, 0, 1, 1, 1],
  });
  const result = parseEptMetadata(minimal);
  expect(result.isEpt).toBe(false);
  if (result.isEpt) return;
  expect(result.reason).toMatch(/X|Y|Z/);
});

test('parseEptMetadata rejects a bounds array of the wrong length', () => {
  const minimal = JSON.stringify({
    version: '1.1.0',
    dataType: 'binary',
    hierarchyType: 'json',
    points: 0,
    span: 128,
    schema: [{ name: 'X', size: 4, type: 'signed' }, { name: 'Y', size: 4, type: 'signed' }, { name: 'Z', size: 4, type: 'signed' }],
    bounds: [0, 0, 0, 1, 1],  // 5 elements — invalid
  });
  const result = parseEptMetadata(minimal);
  expect(result.isEpt).toBe(false);
  if (result.isEpt) return;
  expect(result.reason).toMatch(/bounds/i);
});

// ─────────────────────────────────────────────────────────────────────────────
// Hierarchy parsing
// ─────────────────────────────────────────────────────────────────────────────

test('parseHierarchyFile partitions nodes vs links correctly', () => {
  const text = JSON.stringify({
    '0-0-0-0': 100,
    '1-0-0-0': 50,
    '1-1-0-0': 50,
    '2-0-0-0': -1,   // link — subtree in another file
    '2-3-3-3': 20,
  });
  const result = parseHierarchyFile(text);
  expect(result.entries.length).toBe(5);
  expect(result.nodes.length).toBe(4);   // four entries with positive value
  expect(result.links.length).toBe(1);   // one with -1
  expect(result.totalPoints).toBe(220);  // 100 + 50 + 50 + 20
});

test('parseHierarchyFile rejects a non-numeric value', () => {
  const text = JSON.stringify({ '0-0-0-0': 'oops' });
  expect(() => parseHierarchyFile(text)).toThrow(/non-numeric/);
});

test('parseHierarchyFile rejects a bad address string', () => {
  const text = JSON.stringify({ 'not-an-address': 10 });
  expect(() => parseHierarchyFile(text)).toThrow(/D-X-Y-Z/);
});

test('partitionHierarchyMap helper round-trips a typed map', () => {
  const map = { '0-0-0-0': 50 };
  const result = partitionHierarchyMap(map);
  expect(result.totalPoints).toBe(50);
});

test('synthetic fixture hierarchy file parses cleanly', () => {
  const text = readFileSync(join(FIXTURE_DIR, 'ept-hierarchy', '0-0-0-0.json'), 'utf8');
  const result = parseHierarchyFile(text);
  expect(result.nodes.length).toBe(1);
  expect(result.nodes[0].key).toEqual({ d: 0, x: 0, y: 0, z: 0 });
  expect(result.nodes[0].value).toBe(100);
});

// ─────────────────────────────────────────────────────────────────────────────
// Octree address math
// ─────────────────────────────────────────────────────────────────────────────

test('eptChildKeys produces the 8 standard octree children', () => {
  const root = { d: 0, x: 0, y: 0, z: 0 };
  const children = eptChildKeys(root);
  expect(children.length).toBe(8);
  // Every child is at depth 1 with coords in {0,1}.
  for (const c of children) {
    expect(c.d).toBe(1);
    expect([0, 1]).toContain(c.x);
    expect([0, 1]).toContain(c.y);
    expect([0, 1]).toContain(c.z);
  }
  // The 8 unique coordinate triples cover every {0,1}^3 combination.
  const set = new Set(children.map(eptKeyToString));
  expect(set.size).toBe(8);
});

test('eptKeyToString + eptStringToKey round-trip', () => {
  const k = { d: 5, x: 17, y: 3, z: 200 };
  expect(eptStringToKey(eptKeyToString(k))).toEqual(k);
});

test('eptStringToKey rejects malformed addresses', () => {
  expect(eptStringToKey('not-an-address')).toBeNull();
  expect(eptStringToKey('5-17-3')).toBeNull();        // too few segments
  expect(eptStringToKey('5-17-3-200-extra')).toBeNull(); // too many
  expect(eptStringToKey('5--3-200')).toBeNull();      // empty segment
});

// ─────────────────────────────────────────────────────────────────────────────
// URL construction
// ─────────────────────────────────────────────────────────────────────────────

test('eptBaseUrl strips the ept.json filename and preserves trailing slash', () => {
  expect(eptBaseUrl('https://server/path/ept.json')).toBe('https://server/path/');
  expect(eptBaseUrl('https://server/path/ept.json?token=abc')).toBe('https://server/path/');
  expect(eptBaseUrl('https://server/path/')).toBe('https://server/path/');
});

test('eptRootHierarchyUrl always points at 0-0-0-0', () => {
  expect(eptRootHierarchyUrl('https://s/ept/')).toBe('https://s/ept/ept-hierarchy/0-0-0-0.json');
});

test('eptHierarchyUrl maps a key to the right hierarchy filename', () => {
  expect(eptHierarchyUrl('https://s/ept/', { d: 2, x: 1, y: 0, z: 1 }))
    .toBe('https://s/ept/ept-hierarchy/2-1-0-1.json');
});

test('eptTileUrl maps key + dataType to the right tile path', () => {
  const base = 'https://s/ept/';
  expect(eptTileUrl(base, { d: 0, x: 0, y: 0, z: 0 }, 'laszip'))
    .toBe('https://s/ept/ept-data/0-0-0-0.laz');
  expect(eptTileUrl(base, { d: 1, x: 0, y: 0, z: 1 }, 'binary'))
    .toBe('https://s/ept/ept-data/1-0-0-1.bin');
  expect(eptTileUrl(base, { d: 1, x: 1, y: 1, z: 1 }, 'zstandard'))
    .toBe('https://s/ept/ept-data/1-1-1-1.zst');
});

test('tileExtensionFor returns the canonical extension per dataType', () => {
  expect(tileExtensionFor('laszip')).toBe('laz');
  expect(tileExtensionFor('binary')).toBe('bin');
  expect(tileExtensionFor('zstandard')).toBe('zst');
});

// ─────────────────────────────────────────────────────────────────────────────
// Synthetic fixture — tile size sanity
// ─────────────────────────────────────────────────────────────────────────────

test('synthetic fixture tile size matches the schema-implied byte count', () => {
  // 15 bytes per point × 100 points = 1500 bytes (schema = 4+4+4+2+1).
  const tile = statSync(join(FIXTURE_DIR, 'ept-data', '0-0-0-0.bin'));
  expect(tile.size).toBe(1500);
});
