/**
 * hygienePatterns.test.ts — negative controls for the shipped-file hygiene scan.
 *
 * Proves the secret and narration detectors FAIL on their intended adversarial
 * inputs (so the gate can catch a real leak), and do NOT fire on the legitimate
 * high-entropy / user-intent strings the audit warns against over-flagging.
 */

import { describe, it, expect } from 'vitest';
// @ts-expect-error — plain .mjs helper, no type declarations.
import { findSecret, findNarration, findMarkup, findRoadmapPromise } from '../scripts/lib/hygienePatterns.mjs';

describe('findSecret', () => {
  it('flags high-confidence credential shapes', () => {
    for (const s of [
      '-----BEGIN OPENSSH PRIVATE KEY-----',
      '-----BEGIN RSA PRIVATE KEY-----',
      'const k = "AKIAIOSFODNN7EXAMPLE"',
      'token: ghp_012345678901234567890123456789012345',
      'OPENAI_KEY=sk-abcdef0123456789abcdef0123456789abcdef01',
      'client_secret = "abcdefghijklmnopqrstuvwxyz012345"',
    ]) {
      expect(findSecret(s), s).not.toBeNull();
    }
  });

  it('does NOT flag legitimate high-entropy strings', () => {
    for (const s of [
      '"integrity": "sha512-abcdefABCDEF0123456789+/=abcdefABCDEF0123456789"', // package-lock
      'const wasm = "AGFzbQEAAAAB... (base64)"',
      'a normal sentence mentioning a token or a private network',
      'sha256 = 3b2c1d…', // a plain digest reference
    ]) {
      expect(findSecret(s), s).toBeNull();
    }
  });
});

describe('findNarration', () => {
  it('flags unambiguous assistant-voice narration', () => {
    for (const s of [
      '// As an AI, I generated this',
      '// generated by Claude',
      '// here is the prompt used',
      '// the user asked me to add this',
    ]) {
      expect(findNarration(s), s).not.toBeNull();
    }
  });

  it('does NOT flag legitimate user-intent phrasing in UI code', () => {
    for (const s of [
      '// clamp to the size the user asked for',
      '// the range the user asked to profile',
      '// a system prompt-injection guard for embedded text', // "system prompt" not matched now
    ]) {
      expect(findNarration(s), s).toBeNull();
    }
  });
});

// ── Tool-call markup and roadmap promises ───────────────────────────────────
// A README reached the citable archive ending in two stray closing tags from a
// tool call. The narration family matches prose and the PR scan reads a diff,
// so nothing re-examined a tag committed once. These are the negative controls
// for the two families added to close that: the tags are assembled here rather
// than written literally, so this file does not itself contain what it guards.
describe('tool-call markup never ships', () => {
  const T = (name: string, close = false): string => `<${close ? '/' : ''}${name}>`;

  it('catches a stray closing tool tag, however it is indented', () => {
    for (const line of [T('invoke', true), `   ${T('antml:parameter', true)}`, T('function_calls', true)]) {
      expect(findMarkup(line), line).not.toBeNull();
    }
  });

  it('catches an opening tool tag', () => {
    expect(findMarkup('<invoke name="Bash">')).not.toBeNull();
  });

  it('leaves real markup alone', () => {
    // The tag vocabulary is the whole guard: an HTML, SVG or XML fixture may
    // legitimately close any element, and a scan that cried wolf on those
    // would be turned off.
    for (const line of [T('content', true), T('svg', true), '<div class="content">', T('p', true)]) {
      expect(findMarkup(line), line).toBeNull();
    }
  });
});

describe('a roadmap promise is not a scope statement', () => {
  it('catches a promise about an unbuilt release', () => {
    for (const line of [
      'WebP in a future release',
      'a depth-gradient approximation planned for a later session',
      'deferred to a follow-up cut',
    ]) {
      expect(findRoadmapPromise(line), line).not.toBeNull();
    }
  });

  it('leaves a scope statement alone', () => {
    // These say what the software does NOT do, which is load-bearing honesty.
    for (const line of [
      'Ordered point-for-point verification is future work',
      'streaming highlights are not supported',
      'the holdout has not been run',
    ]) {
      expect(findRoadmapPromise(line), line).toBeNull();
    }
  });
});
