/**
 * hygienePatterns.test.ts — negative controls for the shipped-file hygiene scan.
 *
 * Proves the secret and narration detectors FAIL on their intended adversarial
 * inputs (so the gate can catch a real leak), and do NOT fire on the legitimate
 * high-entropy / user-intent strings the audit warns against over-flagging.
 */

import { describe, it, expect } from 'vitest';
// @ts-expect-error — plain .mjs helper, no type declarations.
import { findSecret, findNarration } from '../scripts/lib/hygienePatterns.mjs';

describe('findSecret', () => {
  it('flags high-confidence credential shapes', () => {
    for (const s of [
      '-----BEGIN OPENSSH PRIVATE KEY-----',
      '-----BEGIN RSA PRIVATE KEY-----',
      'const k = "AKIAIOSFODNN7EXAMPLE"',
      'token: ghp_012345678901234567890123456789012345',
      'OPENAI_KEY=sk-abcdef0123456789abcdef0123456789abcdef01',
      'client_secret = "abcdefghijklmnopqrstuvwxyz012345"',
    ]) {
      expect(findSecret(s), s).not.toBeNull();
    }
  });

  it('does NOT flag legitimate high-entropy strings', () => {
    for (const s of [
      '"integrity": "sha512-abcdefABCDEF0123456789+/=abcdefABCDEF0123456789"', // package-lock
      'const wasm = "AGFzbQEAAAAB... (base64)"',
      'a normal sentence mentioning a token or a private network',
      'sha256 = 3b2c1d…', // a plain digest reference
    ]) {
      expect(findSecret(s), s).toBeNull();
    }
  });
});

describe('findNarration', () => {
  it('flags unambiguous assistant-voice narration', () => {
    for (const s of [
      '// As an AI, I generated this',
      '// generated by Claude',
      '// here is the prompt used',
      '// the user asked me to add this',
    ]) {
      expect(findNarration(s), s).not.toBeNull();
    }
  });

  it('does NOT flag legitimate user-intent phrasing in UI code', () => {
    for (const s of [
      '// clamp to the size the user asked for',
      '// the range the user asked to profile',
      '// a system prompt-injection guard for embedded text', // "system prompt" not matched now
    ]) {
      expect(findNarration(s), s).toBeNull();
    }
  });
});
