/**
 * realSceneGfStratification.test.ts — ground-filter agreement, stratified by raw
 * LAS fields, on real airborne tiles (Track D of the real-scene validation).
 *
 * groundFilterProducerAgreement reports one F1 per scene; it cannot say WHERE
 * the filter's precision collapses. This bins the same confusion by return
 * number and (where intensity is populated) intensity quartile — stratifiers the
 * filter never sees, taken straight from the LAS record, so they cannot be
 * circular. Slope is deliberately excluded: it would come from a DTM the filter
 * itself produced.
 *
 * Exploratory, no accuracy floor. The recorded pattern is a FINDING, not a gate:
 * on the dense-canopy Rogue tile (OLV-DS-091) precision rises with return number
 * (first returns are canopy tops that read as false ground) and falls with
 * intensity; on the montane Jemez tile (OLV-DS-090) precision is flat across
 * return numbers. One pattern does not hold on both scenes, so the test asserts
 * only what must always be true: the strata reconcile to the overall totals,
 * every bin has support, and rates are well-formed. Producer labels are a
 * REFERENCE, not survey truth. The committed oracle
 * (validation/real-scene/gf-strata/<id>.json) is regenerated by
 * scripts/gen-real-scene-gf-strata.mjs; CI reads only the oracle.
 */
import { describe, it, expect } from 'vitest';
import { readFileSync, existsSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const DIR = resolve(ROOT, 'validation/real-scene/gf-strata');

interface Bin { support: number; tp: number; fp: number; fn: number; tn: number; recall: number; precision: number; f1: number; }
interface StrataOracle {
  datasetId: string;
  reference: string;
  overall: Bin;
  byReturnNumber: Record<string, Bin>;
  byIntensityQuartile: (Record<string, Bin> & { cuts: number[] }) | null;
}

const CASES: Array<{ id: string; hasIntensityStrata: boolean }> = [
  { id: 'OLV-DS-090', hasIntensityStrata: false }, // Jemez intensity is all-zero
  { id: 'OLV-DS-091', hasIntensityStrata: true },  // Rogue intensity populated
];

const wellFormed = (b: Bin) => {
  expect(b.support).toBeGreaterThan(0);
  expect(b.support).toBe(b.tp + b.fp + b.fn + b.tn);
  for (const r of [b.recall, b.precision, b.f1]) {
    expect(r).toBeGreaterThanOrEqual(0);
    expect(r).toBeLessThanOrEqual(1);
  }
};

describe('real-scene ground-filter stratification', () => {
  for (const c of CASES) {
    const path = resolve(DIR, `${c.id}.json`);
    const present = existsSync(path);
    const o: StrataOracle | null = present ? JSON.parse(readFileSync(path, 'utf8')) : null;

    describe(c.id, () => {
      it('oracle is committed and references the producer ground class', () => {
        expect(present, `${c.id}.json missing — regenerate with gen-real-scene-gf-strata.mjs`).toBe(true);
        expect(o!.reference).toBe('producer-ground-class-2');
        wellFormed(o!.overall);
      });

      it('return-number strata reconcile to the overall totals', () => {
        const bins = Object.values(o!.byReturnNumber);
        expect(bins.length).toBeGreaterThanOrEqual(2);
        bins.forEach(wellFormed);
        const sum = (pick: (b: Bin) => number) => bins.reduce((a, b) => a + pick(b), 0);
        for (const k of ['support', 'tp', 'fp', 'fn', 'tn'] as const) {
          expect(sum((b) => b[k]), `${c.id} ${k} strata sum != overall`).toBe(o!.overall[k]);
        }
      });

      it(c.hasIntensityStrata ? 'has intensity quartiles that reconcile' : 'has no intensity strata (all-zero intensity)', () => {
        if (!c.hasIntensityStrata) {
          expect(o!.byIntensityQuartile).toBeNull();
          return;
        }
        const q = o!.byIntensityQuartile!;
        expect(q.cuts).toHaveLength(3);
        const bins = ['q1', 'q2', 'q3', 'q4'].map((k) => q[k] as Bin);
        bins.forEach(wellFormed);
        expect(bins.reduce((a, b) => a + b.support, 0)).toBe(o!.overall.support);
      });
    });
  }
});
