/**
 * referenceFixtures.test.ts — the viewer's projection maths against PROJ.
 *
 * Roadmap item P1 #9 (docs/architecture/coordinate-integrity-roadmap.md): every
 * other CRS test in this repository checks the transforms for INTERNAL
 * self-consistency — a forward/inverse round trip returns the input, an anchor
 * matches Snyder's worked example. Those catch sign errors and dropped terms,
 * but a round trip that is wrong in the same way both directions passes them,
 * and Snyder is the same family of series the viewer implements. This file
 * closes that gap: it compares the viewer's output against a table produced by
 * PROJ (pyproj) — an implementation the viewer shares no code with.
 *
 * The reference table is committed at
 * validation/cross-implementation/crs-reference/proj-reference.json and is
 * regenerated by scripts/gen-reference-fixtures.py. pyproj is needed only to
 * REGENERATE it; this test reads the committed JSON and needs no Python.
 *
 * ─────────────────────────────────────────────────────────────────────────────
 * METRIC AND TOLERANCE
 * ─────────────────────────────────────────────────────────────────────────────
 * Horizontal deviation, in metres, between the viewer's easting/northing and the
 * reference easting/northing — the hypotenuse of the two component deltas. The
 * gate is < 1 mm ({@link TOLERANCE_M}). For the inverse direction the viewer
 * returns lon/lat; the residual is converted to ground metres with the WGS84
 * radii of curvature at the fixture latitude, so the same millimetre gate applies
 * in both directions.
 *
 * The inverse leg compares against PROJ's OWN inverse of the committed
 * easting/northing (the fixture's `invLon`/`invLat`), not against the original
 * lon/lat. For an exactly invertible transform (UTM, Web Mercator) these are the
 * same. For EPSG:27700, whose datum leg is a 7-parameter Helmert, the transform
 * is not exactly invertible by negating its parameters — PROJ's own
 * forward->inverse misses the input by ~0.8 mm at UK latitudes — so comparing the
 * viewer's inverse to the original lon/lat would charge the viewer for a
 * non-closure PROJ shares. Comparing to PROJ's inverse keeps the leg a
 * like-for-like cross-implementation check in one direction.
 *
 * The tolerance is NOT relaxed to make a row pass. A fixture that exceeds it is
 * a finding about the transform, reported with its numbers, not a bound to move.
 *
 * ─────────────────────────────────────────────────────────────────────────────
 * WHAT EACH LEG PROVES
 * ─────────────────────────────────────────────────────────────────────────────
 * path 'vendored-utm'  — src/geo/UtmConverter.ts (the hand-written series),
 *   referenced against PROJ AUTHORITY codes (EPSG:4326 -> 326zz/327zz). Both
 *   sides are WGS84, so there is no datum operation and this is a pure
 *   projection cross-check with no shared code and no shared definition source.
 *
 * path 'proj4-engine'  — src/convert/reproject.ts, which delegates to proj4js
 *   after resolving an EPSG code to a curated proj4 string (src/convert/epsg.ts).
 *   Web Mercator (3857) is referenced against PROJ's authority definition
 *   (datum-clean). The national grids (27700, 2154) are referenced against the
 *   viewer's OWN proj4 string fed to PROJ, which holds the datum model identical
 *   on both sides and so checks the curated projection PARAMETERS — false
 *   easting/northing, standard parallels, k0, ellipsoid — rather than datum
 *   realization. The JSON's `reference` field records which method each row used.
 */

import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import { utmConverter } from '../src/geo/UtmConverter';
import { reprojectGlobal } from '../src/convert/reproject';
import type { GlobalPoints } from '../src/convert/globalPoints';
import type { ResolvedCrs } from '../src/geo/CoordinateTypes';

// ─────────────────────────────────────────────────────────────────────────────
// The gate
// ─────────────────────────────────────────────────────────────────────────────

/** Horizontal agreement required against the PROJ reference, in metres. */
const TOLERANCE_M = 1e-3; // 1 mm

// ─────────────────────────────────────────────────────────────────────────────
// The committed reference table
// ─────────────────────────────────────────────────────────────────────────────

interface Fixture {
  readonly id: string;
  readonly path: 'vendored-utm' | 'proj4-engine';
  readonly category: string;
  readonly epsg: number;
  readonly sourceCrs: string;
  readonly referenceCrs: string;
  readonly reference: 'pyproj-authority' | 'pyproj-projstring';
  readonly lon: number;
  readonly lat: number;
  readonly easting: number;
  readonly northing: number;
  /** PROJ's inverse of (easting, northing) — the inverse leg's reference. */
  readonly invLon: number;
  readonly invLat: number;
}

interface ReferenceTable {
  readonly provenance: {
    readonly referenceImplementation: string;
    readonly pyprojVersion: string;
    readonly projVersion: string;
    readonly metric: string;
    readonly toleranceMm: number;
  };
  readonly fixtures: readonly Fixture[];
}

const HERE = dirname(fileURLToPath(import.meta.url));
const REF_PATH = resolve(
  HERE,
  '../validation/cross-implementation/crs-reference/proj-reference.json',
);

const TABLE = JSON.parse(readFileSync(REF_PATH, 'utf8')) as ReferenceTable;

// ─────────────────────────────────────────────────────────────────────────────
// CRS handles + helpers
// ─────────────────────────────────────────────────────────────────────────────

const WGS84_LATLON: ResolvedCrs = {
  kind: 'geographic',
  name: 'WGS 84',
  epsg: 4326,
  linearUnit: 'unknown',
  linearUnitToMetres: 1,
  source: 'las-vlr',
  confidence: 'high',
  userConfirmed: false,
};

function utmCrs(epsg: number): ResolvedCrs {
  return {
    kind: 'projected',
    name: `EPSG:${epsg}`,
    epsg,
    linearUnit: 'metre',
    linearUnitToMetres: 1,
    source: 'las-vlr',
    confidence: 'high',
    userConfirmed: false,
  };
}

// WGS84 ellipsoid, for converting an inverse lon/lat residual into ground metres.
const WGS84_A = 6378137.0;
const WGS84_E2 = 1 - Math.pow(1 - 1 / 298.257223563, 2);
const DEG = Math.PI / 180;

/** Metres per degree of latitude / longitude at a given latitude (WGS84). */
function metresPerDegree(latDeg: number): { perLat: number; perLon: number } {
  const s = Math.sin(latDeg * DEG);
  const w = 1 - WGS84_E2 * s * s;
  const meridional = (WGS84_A * (1 - WGS84_E2)) / Math.pow(w, 1.5); // M
  const primeVertical = WGS84_A / Math.sqrt(w); // N
  return {
    perLat: meridional * DEG,
    perLon: primeVertical * Math.cos(latDeg * DEG) * DEG,
  };
}

/**
 * Ground distance in metres between a viewer lon/lat and a reference lon/lat.
 * The residual is sub-millimetre, so the local linearisation is far more than
 * accurate enough to express it.
 */
function geographicMetres(
  lonOut: number,
  latOut: number,
  refLon: number,
  refLat: number,
): number {
  const { perLat, perLon } = metresPerDegree(refLat);
  const dNorth = (latOut - refLat) * perLat;
  const dEast = (lonOut - refLon) * perLon;
  return Math.hypot(dEast, dNorth);
}

/** A one-point GlobalPoints for the proj4 export engine. */
function onePoint(x: number, y: number): GlobalPoints {
  return {
    count: 1,
    x: Float64Array.from([x]),
    y: Float64Array.from([y]),
    z: Float64Array.from([0]),
  };
}

// ─────────────────────────────────────────────────────────────────────────────
// Deviations, computed once
// ─────────────────────────────────────────────────────────────────────────────

interface Leg {
  readonly fixture: Fixture;
  readonly direction: 'forward' | 'inverse';
  /** Metres, or null when the transform refused (which is itself a failure). */
  readonly deviationM: number | null;
  readonly note?: string;
}

/** Forward: lon/lat -> easting/northing, deviation directly in metres. */
function forwardLeg(fix: Fixture): Leg {
  if (fix.path === 'vendored-utm') {
    const r = utmConverter.convertPoint(
      { x: fix.lon, y: fix.lat, z: 0 },
      WGS84_LATLON,
      utmCrs(fix.epsg),
    );
    if (!r.ok) return { fixture: fix, direction: 'forward', deviationM: null, note: r.reason };
    return {
      fixture: fix,
      direction: 'forward',
      deviationM: Math.hypot(r.value.x - fix.easting, r.value.y - fix.northing),
    };
  }
  // proj4-engine: lon/lat (EPSG:4326) -> projected EPSG.
  const out = reprojectGlobal(onePoint(fix.lon, fix.lat), 4326, fix.epsg);
  if (!out.transformed) return { fixture: fix, direction: 'forward', deviationM: null, note: out.note };
  return {
    fixture: fix,
    direction: 'forward',
    deviationM: Math.hypot(out.points.x[0] - fix.easting, out.points.y[0] - fix.northing),
  };
}

/** Inverse: easting/northing -> lon/lat, deviation converted to ground metres. */
function inverseLeg(fix: Fixture): Leg {
  if (fix.path === 'vendored-utm') {
    const r = utmConverter.convertPoint(
      { x: fix.easting, y: fix.northing, z: 0 },
      utmCrs(fix.epsg),
      WGS84_LATLON,
    );
    if (!r.ok) return { fixture: fix, direction: 'inverse', deviationM: null, note: r.reason };
    // Convention: convertPoint to WGS84 lat/lon returns lon in x, lat in y.
    return {
      fixture: fix,
      direction: 'inverse',
      deviationM: geographicMetres(r.value.x, r.value.y, fix.invLon, fix.invLat),
    };
  }
  const out = reprojectGlobal(onePoint(fix.easting, fix.northing), fix.epsg, 4326);
  if (!out.transformed) return { fixture: fix, direction: 'inverse', deviationM: null, note: out.note };
  return {
    fixture: fix,
    direction: 'inverse',
    deviationM: geographicMetres(out.points.x[0], out.points.y[0], fix.invLon, fix.invLat),
  };
}

const LEGS: Leg[] = TABLE.fixtures.flatMap((f) => [forwardLeg(f), inverseLeg(f)]);

// ─────────────────────────────────────────────────────────────────────────────
// Tests
// ─────────────────────────────────────────────────────────────────────────────

describe('CRS reference fixtures (PROJ / pyproj)', () => {
  it('the committed table declares its provenance and is well formed', () => {
    expect(TABLE.provenance.referenceImplementation).toMatch(/PROJ/);
    expect(TABLE.provenance.pyprojVersion).toMatch(/\d+\.\d+/);
    expect(TABLE.provenance.projVersion).toMatch(/\d+\.\d+/);
    expect(TABLE.provenance.toleranceMm).toBe(1.0);
    expect(TABLE.fixtures.length).toBeGreaterThanOrEqual(20);
    for (const f of TABLE.fixtures) {
      for (const v of [f.lon, f.lat, f.easting, f.northing, f.invLon, f.invLat]) {
        expect(Number.isFinite(v)).toBe(true);
      }
    }
  });

  it('covers both hemispheres, a zone edge, high latitude, and a non-UTM CRS', () => {
    const cats = new Set(TABLE.fixtures.map((f) => f.category));
    expect(cats.has('utm-north')).toBe(true);
    expect(cats.has('utm-south')).toBe(true);
    expect(cats.has('zone-edge')).toBe(true);
    expect(cats.has('high-latitude')).toBe(true);
    // At least one projected CRS that is not UTM (the viewer's export engine
    // supports these via proj4). Web Mercator is the datum-clean one.
    expect(TABLE.fixtures.some((f) => f.path === 'proj4-engine')).toBe(true);
    // The ±80° latitude requirement, in both hemispheres.
    expect(TABLE.fixtures.some((f) => f.lat >= 80)).toBe(true);
    expect(TABLE.fixtures.some((f) => f.lat <= -80)).toBe(true);
    // Several UTM zones across both hemispheres.
    const utmZones = new Set(
      TABLE.fixtures.filter((f) => f.path === 'vendored-utm').map((f) => f.epsg % 100),
    );
    expect(utmZones.size).toBeGreaterThanOrEqual(6);
  });

  it('every transform resolved — a refusal here is a failure, not a skip', () => {
    // A leg with a null deviation means the converter declined the point. That
    // must fail loudly: a silently-skipped leg would let the suite pass having
    // measured nothing, which is the exact failure P1 #9 exists to prevent.
    //
    // The loop below is the same vacuous success one level up: an empty fixture
    // set would let this pass having checked nothing, so assert there is work
    // before checking each leg.
    expect(LEGS.length).toBeGreaterThan(0);
    for (const leg of LEGS) {
      if (leg.deviationM === null) {
        throw new Error(
          `${leg.fixture.id} (${leg.direction}) did not resolve: ${leg.note ?? 'unknown reason'}`,
        );
      }
    }
  });

  // The headline assertion, one row per fixture per direction.
  for (const leg of LEGS) {
    it(`${leg.fixture.id} [${leg.fixture.path}/${leg.direction}] agrees with PROJ within 1 mm`, () => {
      expect(leg.deviationM).not.toBeNull();
      // Do NOT loosen this bound to pass. Beyond it is a transform finding.
      expect(leg.deviationM!).toBeLessThan(TOLERANCE_M);
    });
  }

  it('reports the maximum observed deviation against PROJ', () => {
    let worst: Leg | null = null;
    for (const leg of LEGS) {
      if (leg.deviationM === null) continue;
      if (worst === null || leg.deviationM > (worst.deviationM ?? 0)) worst = leg;
    }
    expect(worst).not.toBeNull();
    const maxM = worst!.deviationM!;
    process.stdout.write(
      `crs-reference: ${LEGS.length} legs over ${TABLE.fixtures.length} fixtures; ` +
        `max deviation ${(maxM * 1000).toExponential(3)} mm ` +
        `at ${worst!.fixture.id} (${worst!.direction}); gate ${TOLERANCE_M * 1000} mm ` +
        `(PROJ ${TABLE.provenance.projVersion}, pyproj ${TABLE.provenance.pyprojVersion})\n`,
    );
    // The whole point of the fixture: the worst case clears the gate.
    expect(maxM).toBeLessThan(TOLERANCE_M);
  });

  // ── negative control ────────────────────────────────────────────────────────
  // A comparison that never fails has not been shown to work. Swapping the
  // reference easting and northing is a metres-scale error the gate must reject,
  // proving the assertion above bites rather than passing vacuously.
  it('rejects a deliberately corrupted reference (easting/northing swapped)', () => {
    const utm = TABLE.fixtures.find((f) => f.path === 'vendored-utm' && f.category === 'utm-north');
    expect(utm).toBeTruthy();
    const r = utmConverter.convertPoint(
      { x: utm!.lon, y: utm!.lat, z: 0 },
      WGS84_LATLON,
      utmCrs(utm!.epsg),
    );
    expect(r.ok).toBe(true);
    if (!r.ok) return;
    const truthful = Math.hypot(r.value.x - utm!.easting, r.value.y - utm!.northing);
    const swapped = Math.hypot(r.value.x - utm!.northing, r.value.y - utm!.easting);
    expect(truthful).toBeLessThan(TOLERANCE_M);
    expect(swapped).toBeGreaterThan(TOLERANCE_M);
  });
});
