/**
 * slopeAspectSpotCheck.test.ts — quick-win 7. An independent slope/aspect check
 * against a NumPy reference on a real DTM.
 *
 * The committed scipy point-in-cell DTM (whitesands-dune__bincell-dtm.asc) is the
 * shared input. A separate NumPy implementation of the same Horn 3x3 convention
 * froze slope and aspect at ~120 deterministic interior cells whose full 3x3
 * neighbourhood is populated (references/whitesands-dune__slope-aspect-spotcheck.json,
 * regenerated by scripts/terrain-field/generate-slope-aspect-spotcheck.py). OLV's
 * production hornSlopeAspect runs on the same grid and must agree at those cells:
 * slope by absolute difference, aspect by circular angular difference (radians).
 *
 * This is complementary to the E4 cross-implementation studies, not a
 * replacement — it is a small, real-data, second-implementation spot-check.
 */

import { describe, it, expect } from 'vitest';
import { existsSync, readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { hornSlopeAspect } from '../src/terrain/ground/terrainDerivatives';
import { readAsciiSouthUp, WS_REF_BINCELL } from './support/terrainField';

const REF = resolve(__dirname, '../validation/terrain-field/references/whitesands-dune__slope-aspect-spotcheck.json');

/** Circular difference of two angles in radians, in [0, π]. */
function circRad(a: number, b: number): number {
  let d = Math.abs(a - b) % (2 * Math.PI);
  if (d > Math.PI) d = 2 * Math.PI - d;
  return d;
}

describe('OLV slope/aspect vs an independent NumPy reference (White Sands DTM)', () => {
  const has = existsSync(WS_REF_BINCELL) && existsSync(REF);

  (has ? it : it.skip)('agrees at the frozen spot-check cells within tolerance', () => {
    const ref = JSON.parse(readFileSync(REF, 'utf8')) as {
      grid: { cols: number; rows: number; cellSizeM: number };
      tolerance: { slopeAbs: number; aspectRad: number };
      cells: Array<{ index: number; slope: number; aspect: number }>;
    };
    const { cols, rows, z } = readAsciiSouthUp(WS_REF_BINCELL);
    const zf = Float32Array.from(z, (v) => (v <= -9998 ? NaN : v)); // nodata → NaN
    expect(cols).toBe(ref.grid.cols);
    expect(rows).toBe(ref.grid.rows);

    const der = hornSlopeAspect(zf, cols, rows, ref.grid.cellSizeM);

    let maxSlope = 0, maxAspect = 0;
    for (const cell of ref.cells) {
      maxSlope = Math.max(maxSlope, Math.abs(der.slope[cell.index] - cell.slope));
      maxAspect = Math.max(maxAspect, circRad(der.aspect[cell.index], cell.aspect));
    }
    // eslint-disable-next-line no-console
    console.log(`[terrain-field] slope/aspect spot-check (${ref.cells.length} cells vs numpy ${(ref as unknown as { version?: string }).version ?? ''}): maxSlopeAbs=${maxSlope.toExponential(2)} maxAspectRad=${maxAspect.toExponential(2)}`);

    expect(ref.cells.length).toBeGreaterThan(50);
    expect(maxSlope).toBeLessThan(ref.tolerance.slopeAbs);
    expect(maxAspect).toBeLessThan(ref.tolerance.aspectRad);
  });
});
