/**
 * snapshotReachabilityStatus.test.ts
 *
 * The reachability producer declares two records: `claims.json` (committed, a
 * tracked input) and `summary.json` (generated by `verify:reachability`, the
 * primary output). On a clean tree the generated summary is absent while the
 * tracked claims file is present. The producer status must then read
 * `not-executed` — nobody ran it — not `failed`, which would misreport an
 * unrun step as a broken one. A `failed` status requires the primary output to
 * be present-but-inconsistent, i.e. evidence the producer actually ran.
 *
 * These drive deriveSnapshot directly with a fake record set so the status
 * inference is exercised without a real repository tree.
 */

import { describe, it, expect } from 'vitest';
// @ts-expect-error — plain .mjs script, no type declarations.
import { deriveSnapshot } from '../scripts/validation-snapshot-lib.mjs';

/** Build the deriveSnapshot fakes from a set of "present" repo-relative paths. */
function snapshotWith(present: Set<string>): {
  producers: Array<{ producerId: string; status: string }>;
} {
  return deriveSnapshot({
    read: () => null,
    has: (p: string) => present.has(p),
    digest: () => ({ sha256: '0'.repeat(64), bytes: 0 }),
    listed: () => [],
    storedPathOf: (p: string) => p,
  });
}

function reachability(snap: { producers: Array<{ producerId: string; status: string }> }) {
  return snap.producers.find((p) => p.producerId === 'reachability');
}

describe('reachability producer status', () => {
  it('is not-executed when only the tracked claims.json is present', () => {
    const snap = snapshotWith(new Set(['validation/reachability/claims.json']));
    expect(reachability(snap)?.status).toBe('not-executed');
  });

  it('is not-executed when nothing is present', () => {
    const snap = snapshotWith(new Set());
    expect(reachability(snap)?.status).toBe('not-executed');
  });

  it('is collected when the primary summary.json is present', () => {
    const snap = snapshotWith(
      new Set([
        'validation/reachability/claims.json',
        'validation/reachability/summary.json',
      ]),
    );
    expect(reachability(snap)?.status).toBe('collected');
  });
});
