/**
 * tests/viewState.test.ts
 *
 * The pure view-state orchestration seam (src/io/viewState.ts) that both the
 * session import/export path and the named saved-view path in main.ts route
 * through — one capture shape, one ordered apply.
 *
 * The ordering contract matters for publishability: a paper figure is
 * regenerated by restoring a named state, and the camera must be applied LAST
 * so no later field (a clip re-fit, a filter-driven re-render, a render-mode
 * change) can nudge the framing after the pose lands. These tests pin that
 * order with a recording sink, and pin the emit-only-when-set pruning that
 * keeps camera-only views byte-identical to their v6 serialisation.
 */

import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import {
  applyViewStateInOrder,
  buildViewState,
  type ViewStateSinks,
} from '../src/io/viewState';
import type { ViewStateBundle } from '../src/io/session';

/** A sink set that records which field was applied, in call order. */
function recordingSinks(calls: string[]): ViewStateSinks {
  return {
    render: () => calls.push('render'),
    colorMode: () => calls.push('colorMode'),
    classFilter: () => calls.push('classFilter'),
    pointFilters: () => calls.push('pointFilters'),
    clip: () => calls.push('clip'),
    camera: () => calls.push('camera'),
  };
}

/** A bundle with every field set. */
function fullBundle(): ViewStateBundle {
  return {
    camera: { position: [1, 2, 3], target: [0, 0, 0] },
    render: {
      pointSize: 2, edlEnabled: true, edlStrength: 0.5,
      pointSizeMode: 'adaptive', antialiasing: true,
    },
    colorMode: 'elevation',
    classFilter: [2, 6],
    pointFilters: { elevation: [0, 10] },
    clip: {
      box: { min: [0, 0, 0], max: [1, 1, 1] },
      mode: 'keep-inside',
      enabled: true,
    },
  };
}

describe('applyViewStateInOrder — the single ordered apply path', () => {
  it('applies the camera LAST, after every display field', () => {
    const calls: string[] = [];
    applyViewStateInOrder(fullBundle(), recordingSinks(calls));
    expect(calls).toHaveLength(6);
    expect(calls[calls.length - 1]).toBe('camera');
    expect(calls).toEqual([
      'render', 'colorMode', 'classFilter', 'pointFilters', 'clip', 'camera',
    ]);
  });

  it('guards every field independently — an empty bundle fires no sink', () => {
    const calls: string[] = [];
    applyViewStateInOrder({}, recordingSinks(calls));
    expect(calls).toEqual([]);
  });

  it('a partial bundle fires only the sinks for the fields it carries', () => {
    const calls: string[] = [];
    applyViewStateInOrder(
      { clip: fullBundle().clip, colorMode: 'intensity' },
      recordingSinks(calls),
    );
    expect(calls).toEqual(['colorMode', 'clip']);
  });

  it('a camera-only bundle fires only the camera sink (pre-v7 view semantics)', () => {
    const calls: string[] = [];
    applyViewStateInOrder({ camera: fullBundle().camera }, recordingSinks(calls));
    expect(calls).toEqual(['camera']);
  });

  it('an empty classFilter never fires the class sink', () => {
    const calls: string[] = [];
    applyViewStateInOrder(
      { classFilter: [], camera: fullBundle().camera },
      recordingSinks(calls),
    );
    expect(calls).toEqual(['camera']);
  });
});

describe('buildViewState — emit-only-when-set pruning', () => {
  it('returns undefined when nothing is set', () => {
    expect(buildViewState({})).toBeUndefined();
  });

  it('drops an empty classFilter and a window-less pointFilters block', () => {
    expect(buildViewState({ classFilter: [], pointFilters: {} })).toBeUndefined();
  });

  it('keeps exactly the fields that are set', () => {
    const pruned = buildViewState({
      classFilter: [],
      pointFilters: { intensity: [5, 50] },
      colorMode: 'rgb',
    });
    expect(pruned).toEqual({ pointFilters: { intensity: [5, 50] }, colorMode: 'rgb' });
  });

  it('a full bundle passes through intact', () => {
    expect(buildViewState(fullBundle())).toEqual(fullBundle());
  });
});

describe('main.ts scan-lifecycle reset sites still clear saved views', () => {
  it('every reset site clears savedViews together with its counter', () => {
    // Source-shape contract (same spirit as scripts/lint-main-deferral.mjs):
    // the three scan-lifecycle resets — new static scan, streaming open, and
    // close-to-empty-state — must all drop the saved views AND rewind the
    // name counter, or a stale "north-scarp" from the previous scan would
    // restore a state that was never captured against the open one.
    const src = readFileSync(new URL('../src/main.ts', import.meta.url), 'utf8');
    const resets = src.match(/savedViews = \[\];\s*\n\s*viewCounter = 0;/g) ?? [];
    expect(resets.length).toBeGreaterThanOrEqual(3);
  });
});
