/**
 * classifierCorpus.ts — the frozen synthetic corpus the derived classifier is
 * measured on, and the reducer that turns one run into per-class numbers.
 *
 * ─────────────────────────────────────────────────────────────────────────────
 * WHAT THIS IS EVIDENCE FOR, AND WHAT IT IS NOT
 * ─────────────────────────────────────────────────────────────────────────────
 * Every scene here is generated by this file. The labels are known because this
 * file wrote them, which makes the result one implementation measured against a
 * generator the same project also wrote. That is synthetic evidence about
 * BEHAVIOUR — where the rules break and by how much — and it is not field
 * validation, not survey truth, and not a statement about accuracy on real
 * scans. Returns are uniform-random in plan with no sensor geometry, no scan
 * pattern, no range noise, and objects that are boxes and clumps of points.
 * A number produced here describes the classifier on these scenes and nothing
 * beyond them.
 *
 * ─────────────────────────────────────────────────────────────────────────────
 * WHY IT IS FROZEN
 * ─────────────────────────────────────────────────────────────────────────────
 * A corpus that drifts turns every metric into an unfalsifiable claim: a recall
 * that rose because the generator changed reads exactly like one that rose
 * because the classifier improved. So generation is deterministic — one
 * written-out linear congruential generator per scene, seeded by an integer, no
 * clock and no ambient randomness — and every coordinate is quantised to
 * millimetres before it enters a buffer, so a float that evaluates differently
 * on another platform cannot move a label.
 *
 * {@link corpusDigest} folds the whole corpus into one hash. `CORPUS_DIGEST` in
 * `tests/classifierCorpus.test.ts` pins it, so any edit to a scene, a seed, a
 * density or a label fails that test rather than quietly rewriting the baseline
 * the metrics are read against. This mirrors the discipline
 * `scripts/verify-validation-snapshot.mjs` applies to the validation snapshot:
 * the record is checked against a recomputation, not against itself.
 *
 * Pure data: no DOM, no three.js, no I/O, no timers. The classifier is NOT
 * imported here — this module builds scenes and scores label arrays, and the
 * runner is what calls the classifier, so a pure layer stays pure.
 */

import { sha256 } from '../render/measure/auditLog';

/** The corpus revision. Bump when a scene, a seed or a label rule changes. */
export const CORPUS_VERSION = 1;

/** ASPRS codes the corpus labels and the classifier can emit. */
export const TRUTH_GROUND = 2;
export const TRUTH_LOW_VEG = 3;
export const TRUTH_MED_VEG = 4;
export const TRUTH_HIGH_VEG = 5;
export const TRUTH_BUILDING = 6;
/**
 * ASPRS 7 (low point / noise). The corpus labels gross below-ground blunders
 * this way and the classifier CANNOT emit it, so those points are always
 * counted as errors somewhere. That asymmetry is deliberate and is reported,
 * never averaged away: a filter that calls a multipath return "ground" has made
 * a mistake whatever a one-sided height test decides.
 */
export const TRUTH_LOW_NOISE = 7;

/** Predicted code for "the classifier declined to name a class". */
export const PREDICTED_UNCLASSIFIED = 1;

/**
 * The classes macro-F1 averages over: the five the classifier can emit. Fixed
 * and frozen, so the average cannot be improved by changing what it covers.
 */
export const SCORED_CLASSES: readonly number[] = Object.freeze([
  TRUTH_GROUND,
  TRUTH_LOW_VEG,
  TRUTH_MED_VEG,
  TRUTH_HIGH_VEG,
  TRUTH_BUILDING,
]);

/** Which required capability a scene exercises. One scene may cover several. */
export type CorpusCategory =
  | 'aerial-urban'
  | 'aerial-vegetation'
  | 'scan-edge-void'
  | 'walls-roofs'
  | 'low-vegetation'
  | 'steep-terrain'
  | 'rolling-terrain'
  | 'low-outliers'
  | 'rgb-absent'
  | 'returns-absent'
  | 'unit-metre'
  | 'unit-foot';

/** The linear unit a scene's coordinates are expressed in. */
export type CorpusUnit = 'metre' | 'usSurveyFoot';

/** One generated scene: the buffers a run needs, plus its ground truth. */
export interface CorpusScene {
  readonly id: string;
  readonly categories: readonly CorpusCategory[];
  readonly unit: CorpusUnit;
  /** Metres per one coordinate unit (1 for metre, 0.3048006096… for the foot). */
  readonly unitToMetre: number;
  readonly description: string;
  readonly count: number;
  readonly xyz: Float32Array;
  /** Truth code per point (ASPRS; {@link TRUTH_LOW_NOISE} for blunders). */
  readonly truth: Uint8Array;
  /** RGB triplets, or null when the scene carries no colour. */
  readonly colors: Uint8Array | null;
  /** LAS return dimensions, or null when the scene carries none. */
  readonly returnNumber: Uint8Array | null;
  readonly returnCount: Uint8Array | null;
  /** Grid cell size to run at, in the scene's own linear unit. */
  readonly cellSize: number;
}

// ── deterministic generation ────────────────────────────────────────────────

/**
 * A 32-bit linear congruential generator (Numerical Recipes constants).
 *
 * Written out rather than imported so the corpus bytes depend on nothing that
 * can be upgraded underneath them, the same reason
 * `scripts/generate-point-cloud-fixtures.mjs` writes its own.
 */
export function lcg(seed: number): () => number {
  let s = seed >>> 0;
  return () => {
    s = (Math.imul(s, 1664525) + 1013904223) >>> 0;
    return s / 4294967296;
  };
}

/** Quantise to millimetres, so no float difference can move a label. */
const q = (v: number): number => Math.round(v * 1000) / 1000;

/** Metres in one US survey foot — the corpus's only unit conversion. */
export const US_SURVEY_FOOT_M = 1200 / 3937;

/** The bare-earth surfaces, in metres. Base 100 m so nothing sits near zero. */
const SURFACES = {
  /** A 2 % tilt with no symmetry axis. Well inside the 15 % slope tolerance. */
  flat: (x: number, y: number): number => 100 + 0.02 * x + 0.01 * y,
  /** Two incommensurate wavelengths: local relief the window ladder must cross. */
  rolling: (x: number, y: number): number =>
    100 + 3 * Math.sin((2 * Math.PI * x) / 25) * Math.cos((2 * Math.PI * y) / 31) + 0.02 * x,
  /** A 30 % V ridge — twice the slope tolerance the defaults encode. */
  ridge: (x: number, y: number): number => 100 + 0.3 * Math.abs(x - 20) + 0.01 * y,
} as const;

type SurfaceName = keyof typeof SURFACES;

const GREY: readonly [number, number, number] = [140, 140, 140];
const GREEN: readonly [number, number, number] = [45, 165, 55];
const ROOF: readonly [number, number, number] = [150, 130, 120];

/** Scene extent in metres, square. */
const EXTENT_M = 40;
/** Bare-earth returns per square metre. */
const GROUND_DENSITY = 5;
/** Roof returns per square metre — denser, as a real roof is. */
const ROOF_DENSITY = 9;

interface Box {
  readonly x0: number;
  readonly y0: number;
  readonly w: number;
  readonly d: number;
  readonly h: number;
}

/** A mutable point accumulator; converted to typed arrays once per scene. */
interface Accum {
  x: number[];
  y: number[];
  z: number[];
  r: number[];
  g: number[];
  b: number[];
  rn: number[];
  rc: number[];
  truth: number[];
}

const accum = (): Accum => ({ x: [], y: [], z: [], r: [], g: [], b: [], rn: [], rc: [], truth: [] });

function add(
  a: Accum,
  x: number,
  y: number,
  z: number,
  rgb: readonly [number, number, number],
  rn: number,
  rc: number,
  truth: number,
): void {
  a.x.push(q(x));
  a.y.push(q(y));
  a.z.push(q(z));
  a.r.push(rgb[0]);
  a.g.push(rgb[1]);
  a.b.push(rgb[2]);
  a.rn.push(rn);
  a.rc.push(rc);
  a.truth.push(truth);
}

const inBox = (x: number, y: number, b: Box): boolean =>
  x >= b.x0 && x <= b.x0 + b.w && y >= b.y0 && y <= b.y0 + b.d;

const inRect = (
  x: number,
  y: number,
  r: { x0: number; y0: number; x1: number; y1: number },
): boolean => x >= r.x0 && x <= r.x1 && y >= r.y0 && y <= r.y1;

/** Options one scene is built from. Every field is explicit; nothing defaults. */
interface SceneSpec {
  readonly id: string;
  readonly categories: readonly CorpusCategory[];
  readonly description: string;
  readonly seed: number;
  readonly surface: SurfaceName;
  readonly buildings: readonly Box[];
  /** Sample the vertical faces of every building as well as the roof. */
  readonly walls: boolean;
  readonly vegClumps: number;
  /** Height band above ground the vegetation clumps occupy, in metres. */
  readonly vegMinH: number;
  readonly vegMaxH: number;
  /** A rectangle with no returns at all, in metres, or null. */
  readonly void: { x0: number; y0: number; x1: number; y1: number } | null;
  /** Gross below-ground returns: how many, and how far under, in metres. */
  readonly blunders: number;
  readonly blunderDepthM: number;
  readonly colors: boolean;
  readonly returns: boolean;
  readonly unit: CorpusUnit;
}

/**
 * Build one scene from its spec. Deterministic: the seed is the only source of
 * variation, and the draw ORDER below is part of the frozen corpus — moving a
 * loop changes every subsequent coordinate.
 */
function buildScene(spec: SceneSpec): CorpusScene {
  const rnd = lcg(spec.seed);
  const surface = SURFACES[spec.surface];
  const a = accum();

  // ── bare earth ───────────────────────────────────────────────────────────
  const groundN = Math.round(EXTENT_M * EXTENT_M * GROUND_DENSITY);
  for (let i = 0; i < groundN; i++) {
    const x = rnd() * EXTENT_M;
    const y = rnd() * EXTENT_M;
    if (spec.void && inRect(x, y, spec.void)) continue;
    if (spec.buildings.some((b) => inBox(x, y, b))) continue;
    add(a, x, y, surface(x, y), GREY, 1, 1, TRUTH_GROUND);
  }

  // ── buildings: flat roofs, and the vertical faces when asked ─────────────
  for (const b of spec.buildings) {
    const roofN = Math.round(b.w * b.d * ROOF_DENSITY);
    for (let i = 0; i < roofN; i++) {
      const x = b.x0 + rnd() * b.w;
      const y = b.y0 + rnd() * b.d;
      add(a, x, y, surface(b.x0, b.y0) + b.h, ROOF, 1, 1, TRUTH_BUILDING);
    }
    if (!spec.walls) continue;
    // Four faces, sampled on a fixed lattice so a wall is a wall on every run.
    const step = 0.5;
    for (let s = 0; s <= b.w; s += step) {
      for (let h = 0.25; h < b.h; h += 0.5) {
        add(a, b.x0 + s, b.y0, surface(b.x0, b.y0) + h, ROOF, 1, 1, TRUTH_BUILDING);
        add(a, b.x0 + s, b.y0 + b.d, surface(b.x0, b.y0) + h, ROOF, 1, 1, TRUTH_BUILDING);
      }
    }
    for (let s = step; s < b.d; s += step) {
      for (let h = 0.25; h < b.h; h += 0.5) {
        add(a, b.x0, b.y0 + s, surface(b.x0, b.y0) + h, ROOF, 1, 1, TRUTH_BUILDING);
        add(a, b.x0 + b.w, b.y0 + s, surface(b.x0, b.y0) + h, ROOF, 1, 1, TRUTH_BUILDING);
      }
    }
  }

  // ── vegetation ───────────────────────────────────────────────────────────
  const CLUMP_RADIUS_M = 1.6;
  const CLUMP_POINTS = 16;
  for (let c = 0; c < spec.vegClumps; c++) {
    const cx = rnd() * EXTENT_M;
    const cy = rnd() * EXTENT_M;
    if (spec.void && inRect(cx, cy, spec.void)) continue;
    if (spec.buildings.some((b) => inBox(cx, cy, b))) continue;
    for (let i = 0; i < CLUMP_POINTS; i++) {
      const x = cx + (rnd() * 2 - 1) * CLUMP_RADIUS_M;
      const y = cy + (rnd() * 2 - 1) * CLUMP_RADIUS_M;
      const h = spec.vegMinH + rnd() * (spec.vegMaxH - spec.vegMinH);
      // Truth follows the SAME height bands the classifier uses, so a band
      // disagreement is a real disagreement and not a definition mismatch.
      const truth = h < 2 ? TRUTH_LOW_VEG : h < 5 ? TRUTH_MED_VEG : TRUTH_HIGH_VEG;
      // A canopy return is one of several from a pulse that kept going; a roof
      // return is not. Second return of two, so the cue reads `returnCount > 1`.
      add(a, x, y, surface(x, y) + h, GREEN, 2, 2, truth);
    }
  }

  // ── gross below-ground blunders ──────────────────────────────────────────
  for (let i = 0; i < spec.blunders; i++) {
    const x = rnd() * EXTENT_M;
    const y = rnd() * EXTENT_M;
    add(a, x, y, surface(x, y) - spec.blunderDepthM, GREY, 1, 1, TRUTH_LOW_NOISE);
  }

  // ── pack, converting the unit last so the geometry is identical ──────────
  const scale = spec.unit === 'usSurveyFoot' ? 1 / US_SURVEY_FOOT_M : 1;
  const count = a.x.length;
  const positions = new Float32Array(count * 3);
  for (let i = 0; i < count; i++) {
    positions[i * 3] = q(a.x[i] * scale);
    positions[i * 3 + 1] = q(a.y[i] * scale);
    positions[i * 3 + 2] = q(a.z[i] * scale);
  }
  const truth = Uint8Array.from(a.truth);
  let colors: Uint8Array | null = null;
  if (spec.colors) {
    colors = new Uint8Array(count * 3);
    for (let i = 0; i < count; i++) {
      colors[i * 3] = a.r[i];
      colors[i * 3 + 1] = a.g[i];
      colors[i * 3 + 2] = a.b[i];
    }
  }
  const returnNumber = spec.returns ? Uint8Array.from(a.rn) : null;
  const returnCount = spec.returns ? Uint8Array.from(a.rc) : null;

  return {
    id: spec.id,
    categories: spec.categories,
    unit: spec.unit,
    unitToMetre: spec.unit === 'usSurveyFoot' ? US_SURVEY_FOOT_M : 1,
    description: spec.description,
    count,
    xyz: positions,
    truth,
    colors,
    returnNumber,
    returnCount,
    cellSize: q(1 * scale),
  };
}

/** Three flat-roof buildings, clear of one another and of the extent border. */
const URBAN_BUILDINGS: readonly Box[] = Object.freeze([
  { x0: 5, y0: 6, w: 8, d: 6, h: 5.5 },
  { x0: 24, y0: 9, w: 7, d: 6, h: 4.0 },
  { x0: 14, y0: 26, w: 9, d: 7, h: 7.0 },
]);

/** The scene matrix. Order is part of the corpus digest. */
const SPECS: readonly SceneSpec[] = Object.freeze([
  {
    id: 'aerial-urban',
    categories: ['aerial-urban', 'unit-metre'],
    description: 'Gentle bare earth, three flat-roof buildings, scattered canopy. Colour and return dimensions both present.',
    seed: 2001, surface: 'flat', buildings: URBAN_BUILDINGS, walls: false,
    vegClumps: 18, vegMinH: 1.2, vegMaxH: 8, void: null, blunders: 0, blunderDepthM: 0,
    colors: true, returns: true, unit: 'metre',
  },
  {
    id: 'aerial-vegetation',
    categories: ['aerial-vegetation'],
    description: 'Gentle bare earth under dense canopy, no structures. The scene where a ground filter has few ground hits to work from.',
    seed: 2002, surface: 'flat', buildings: [], walls: false,
    vegClumps: 60, vegMinH: 1.2, vegMaxH: 9, void: null, blunders: 0, blunderDepthM: 0,
    colors: true, returns: true, unit: 'metre',
  },
  {
    id: 'scan-edge-void',
    categories: ['scan-edge-void'],
    description: 'The urban scene with a 12 m square hole with no returns, so heights near it are sampled against interpolated ground.',
    seed: 2003, surface: 'flat', buildings: URBAN_BUILDINGS, walls: false,
    vegClumps: 18, vegMinH: 1.2, vegMaxH: 8,
    void: { x0: 18, y0: 18, x1: 30, y1: 30 }, blunders: 0, blunderDepthM: 0,
    colors: true, returns: true, unit: 'metre',
  },
  {
    id: 'walls-roofs',
    categories: ['walls-roofs'],
    description: 'The urban buildings with their vertical faces sampled as well as their roofs — the returns a roughness cue reads as rough.',
    seed: 2004, surface: 'flat', buildings: URBAN_BUILDINGS, walls: true,
    vegClumps: 8, vegMinH: 1.2, vegMaxH: 8, void: null, blunders: 0, blunderDepthM: 0,
    colors: true, returns: true, unit: 'metre',
  },
  {
    id: 'low-vegetation',
    categories: ['low-vegetation'],
    description: 'Bare earth under shrub-height cover only (0.6 to 1.9 m), the band that sits just above the ground band.',
    seed: 2005, surface: 'flat', buildings: [], walls: false,
    vegClumps: 55, vegMinH: 0.6, vegMaxH: 1.9, void: null, blunders: 0, blunderDepthM: 0,
    colors: true, returns: true, unit: 'metre',
  },
  {
    id: 'steep-terrain',
    categories: ['steep-terrain', 'rgb-absent', 'returns-absent'],
    description: 'A 30 % V ridge with scattered canopy and no structures. Geometry only: neither colour nor return dimensions.',
    seed: 2006, surface: 'ridge', buildings: [], walls: false,
    vegClumps: 20, vegMinH: 1.2, vegMaxH: 8, void: null, blunders: 0, blunderDepthM: 0,
    colors: false, returns: false, unit: 'metre',
  },
  {
    id: 'rolling-terrain',
    categories: ['rolling-terrain', 'rgb-absent', 'returns-absent'],
    description: 'Rolling bare earth with two incommensurate wavelengths and scattered canopy. Local relief the morphological window has to cross.',
    seed: 2007, surface: 'rolling', buildings: [], walls: false,
    vegClumps: 20, vegMinH: 1.2, vegMaxH: 8, void: null, blunders: 0, blunderDepthM: 0,
    colors: false, returns: false, unit: 'metre',
  },
  {
    id: 'low-outliers',
    categories: ['low-outliers'],
    description: 'The urban scene plus 30 gross returns four metres below the surface — multipath, water, sensor noise.',
    seed: 2008, surface: 'flat', buildings: URBAN_BUILDINGS, walls: false,
    vegClumps: 18, vegMinH: 1.2, vegMaxH: 8, void: null, blunders: 30, blunderDepthM: 4,
    colors: true, returns: true, unit: 'metre',
  },
  {
    id: 'urban-no-rgb',
    categories: ['rgb-absent', 'aerial-urban'],
    description: 'The urban scene with the return dimensions but no colour, so the greenness cue is off and geometry plus returns decide.',
    seed: 2001, surface: 'flat', buildings: URBAN_BUILDINGS, walls: false,
    vegClumps: 18, vegMinH: 1.2, vegMaxH: 8, void: null, blunders: 0, blunderDepthM: 0,
    colors: false, returns: true, unit: 'metre',
  },
  {
    id: 'vegetation-no-returns',
    categories: ['returns-absent', 'aerial-vegetation'],
    description: 'The dense-canopy scene with colour but no return dimensions, so the multi-return cue is off.',
    seed: 2002, surface: 'flat', buildings: [], walls: false,
    vegClumps: 60, vegMinH: 1.2, vegMaxH: 9, void: null, blunders: 0, blunderDepthM: 0,
    colors: true, returns: false, unit: 'metre',
  },
  {
    id: 'units-metre',
    categories: ['unit-metre'],
    description: 'A mixed scene in metres. Paired with units-foot, which is the same geometry in US survey feet.',
    seed: 2011, surface: 'flat', buildings: URBAN_BUILDINGS, walls: false,
    vegClumps: 24, vegMinH: 0.8, vegMaxH: 8, void: null, blunders: 0, blunderDepthM: 0,
    colors: true, returns: true, unit: 'metre',
  },
  {
    id: 'units-foot',
    categories: ['unit-foot'],
    description: 'The units-metre geometry expressed in US survey feet, run with every length parameter scaled to match. A metric that differs from its metre twin is a unit bug, not terrain.',
    seed: 2011, surface: 'flat', buildings: URBAN_BUILDINGS, walls: false,
    vegClumps: 24, vegMinH: 0.8, vegMaxH: 8, void: null, blunders: 0, blunderDepthM: 0,
    colors: true, returns: true, unit: 'usSurveyFoot',
  },
]);

/** Build the whole corpus. Deterministic; cheap enough to call per test. */
export function buildCorpus(): readonly CorpusScene[] {
  return SPECS.map(buildScene);
}

/** The scene ids, in corpus order. */
export const CORPUS_SCENE_IDS: readonly string[] = Object.freeze(SPECS.map((s) => s.id));

/**
 * The classifier parameters that carry a LENGTH and therefore have to be
 * restated in the scene's own unit. `slope` is a ratio, the support gates and
 * the greenness threshold are fractions, and `maxGridDim` is a cell count, so
 * none of them scale.
 */
export const LENGTH_PARAM_KEYS: readonly string[] = Object.freeze([
  'maxObjectSizeM',
  'elevThresholdM',
  'groundBandM',
  'lowVegBandM',
  'medVegBandM',
  'buildingRoughnessMaxM',
  'buildingMinHagM',
]);

/**
 * Restate metre-valued parameters in the scene's linear unit. A caller running
 * a foot cloud has to do exactly this; the corpus does it so the foot scene
 * measures the CLASSIFIER rather than measuring a caller who forgot.
 */
export function scaleLengthParams<T extends object>(
  params: T,
  scene: CorpusScene,
): Record<string, number> {
  const source = params as Readonly<Record<string, unknown>>;
  const out: Record<string, number> = {};
  for (const key of LENGTH_PARAM_KEYS) {
    const value = source[key];
    if (typeof value === 'number') out[key] = value / scene.unitToMetre;
  }
  return out;
}

// ── the hash pin ────────────────────────────────────────────────────────────

/**
 * One scene's digest: every coordinate as a millimetre integer, every label,
 * every colour and return byte, in point order. Hashing the QUANTISED integers
 * rather than the float text means the digest is a property of the geometry and
 * not of a formatter.
 */
export function sceneDigest(scene: CorpusScene): string {
  const parts: string[] = [
    scene.id,
    scene.unit,
    String(scene.count),
    String(scene.cellSize),
  ];
  for (let i = 0; i < scene.count; i++) {
    parts.push(
      `${Math.round(scene.xyz[i * 3] * 1000)},` +
        `${Math.round(scene.xyz[i * 3 + 1] * 1000)},` +
        `${Math.round(scene.xyz[i * 3 + 2] * 1000)},` +
        `${scene.truth[i]},` +
        `${scene.colors ? scene.colors[i * 3] : -1}:` +
        `${scene.colors ? scene.colors[i * 3 + 1] : -1}:` +
        `${scene.colors ? scene.colors[i * 3 + 2] : -1},` +
        `${scene.returnNumber ? scene.returnNumber[i] : -1}:` +
        `${scene.returnCount ? scene.returnCount[i] : -1}`,
    );
  }
  return `sha256:${sha256(parts.join('\n'))}`;
}

/**
 * The corpus digest: the version, then every scene's id and digest, folded into
 * one hash. Per-scene digests are hashed rather than one giant string so a
 * failure names the scene that moved.
 */
export function corpusDigest(scenes: readonly CorpusScene[]): string {
  const lines = [`corpus-v${CORPUS_VERSION}`];
  for (const scene of scenes) lines.push(`${scene.id} ${sceneDigest(scene)}`);
  return `sha256:${sha256(lines.join('\n'))}`;
}

// ── the reducer ─────────────────────────────────────────────────────────────

/** Per-class counts and rates. A metric with no denominator is null, never 0. */
export interface ClassMetrics {
  readonly code: number;
  /** Points whose TRUTH is this class. */
  readonly support: number;
  /** Points PREDICTED this class. */
  readonly predicted: number;
  readonly truePositive: number;
  readonly falsePositive: number;
  readonly falseNegative: number;
  readonly precision: number | null;
  readonly recall: number | null;
  readonly f1: number | null;
}

/** One scene's score. */
export interface SceneScore {
  readonly sceneId: string;
  readonly points: number;
  readonly byClass: readonly ClassMetrics[];
  /**
   * Mean F1 over {@link SCORED_CLASSES}, counting a class with support but no
   * defined F1 as 0 and skipping a class with neither support nor predictions.
   * Null when no scored class has either.
   */
  readonly macroF1: number | null;
  /** Fraction of points the classifier declined to name. */
  readonly unclassifiedRate: number;
  /**
   * Points predicted BUILDING whose truth is not building, over all points
   * whose truth is not building. A false-positive rate, so it does not move
   * when the scene's building count changes.
   */
  readonly falseBuildingRate: number | null;
  /** Points labelled {@link TRUTH_LOW_NOISE} that the run called ground. */
  readonly lowNoiseCalledGround: number;
  readonly lowNoisePoints: number;
}

/** Score one run of the classifier against a scene's labels. */
export function scoreScene(
  sceneId: string,
  truth: Uint8Array,
  predicted: Uint8Array,
): SceneScore {
  const n = Math.min(truth.length, predicted.length);
  const byClass: ClassMetrics[] = [];
  for (const code of SCORED_CLASSES) {
    let tp = 0;
    let fp = 0;
    let fn = 0;
    let support = 0;
    let predictedN = 0;
    for (let i = 0; i < n; i++) {
      const t = truth[i] === code;
      const p = predicted[i] === code;
      if (t) support++;
      if (p) predictedN++;
      if (t && p) tp++;
      else if (p) fp++;
      else if (t) fn++;
    }
    const precision = tp + fp > 0 ? tp / (tp + fp) : null;
    const recall = tp + fn > 0 ? tp / (tp + fn) : null;
    const f1 =
      precision !== null && recall !== null && precision + recall > 0
        ? (2 * precision * recall) / (precision + recall)
        : precision !== null && recall !== null
          ? 0
          : null;
    byClass.push({
      code,
      support,
      predicted: predictedN,
      truePositive: tp,
      falsePositive: fp,
      falseNegative: fn,
      precision,
      recall,
      f1,
    });
  }

  let f1Sum = 0;
  let f1N = 0;
  for (const m of byClass) {
    if (m.support === 0 && m.predicted === 0) continue;
    f1Sum += m.f1 ?? 0;
    f1N++;
  }

  let unclassified = 0;
  let notBuilding = 0;
  let falseBuilding = 0;
  let lowNoisePoints = 0;
  let lowNoiseCalledGround = 0;
  for (let i = 0; i < n; i++) {
    if (predicted[i] === PREDICTED_UNCLASSIFIED) unclassified++;
    if (truth[i] !== TRUTH_BUILDING) {
      notBuilding++;
      if (predicted[i] === TRUTH_BUILDING) falseBuilding++;
    }
    if (truth[i] === TRUTH_LOW_NOISE) {
      lowNoisePoints++;
      if (predicted[i] === TRUTH_GROUND) lowNoiseCalledGround++;
    }
  }

  return {
    sceneId,
    points: n,
    byClass,
    macroF1: f1N > 0 ? f1Sum / f1N : null,
    unclassifiedRate: n > 0 ? unclassified / n : 0,
    falseBuildingRate: notBuilding > 0 ? falseBuilding / notBuilding : null,
    lowNoiseCalledGround,
    lowNoisePoints,
  };
}

/**
 * Pool per-class counts across scenes and rebuild the rates from the totals.
 * Pooling the COUNTS rather than averaging the rates keeps a small scene from
 * weighing the same as a large one.
 */
export function poolScores(scores: readonly SceneScore[]): SceneScore {
  const byCode = new Map<number, { tp: number; fp: number; fn: number; support: number; predicted: number }>();
  for (const code of SCORED_CLASSES) {
    byCode.set(code, { tp: 0, fp: 0, fn: 0, support: 0, predicted: 0 });
  }
  let points = 0;
  let unclassified = 0;
  let notBuilding = 0;
  let falseBuilding = 0;
  let lowNoisePoints = 0;
  let lowNoiseCalledGround = 0;
  for (const s of scores) {
    points += s.points;
    unclassified += Math.round(s.unclassifiedRate * s.points);
    lowNoisePoints += s.lowNoisePoints;
    lowNoiseCalledGround += s.lowNoiseCalledGround;
    for (const m of s.byClass) {
      const acc = byCode.get(m.code);
      if (!acc) continue;
      acc.tp += m.truePositive;
      acc.fp += m.falsePositive;
      acc.fn += m.falseNegative;
      acc.support += m.support;
      acc.predicted += m.predicted;
      if (m.code === TRUTH_BUILDING) {
        notBuilding += s.points - m.support;
        falseBuilding += m.falsePositive;
      }
    }
  }

  const byClass: ClassMetrics[] = SCORED_CLASSES.map((code) => {
    const acc = byCode.get(code)!;
    const precision = acc.tp + acc.fp > 0 ? acc.tp / (acc.tp + acc.fp) : null;
    const recall = acc.tp + acc.fn > 0 ? acc.tp / (acc.tp + acc.fn) : null;
    const f1 =
      precision !== null && recall !== null && precision + recall > 0
        ? (2 * precision * recall) / (precision + recall)
        : precision !== null && recall !== null
          ? 0
          : null;
    return {
      code,
      support: acc.support,
      predicted: acc.predicted,
      truePositive: acc.tp,
      falsePositive: acc.fp,
      falseNegative: acc.fn,
      precision,
      recall,
      f1,
    };
  });

  let f1Sum = 0;
  let f1N = 0;
  for (const m of byClass) {
    if (m.support === 0 && m.predicted === 0) continue;
    f1Sum += m.f1 ?? 0;
    f1N++;
  }

  return {
    sceneId: 'pooled',
    points,
    byClass,
    macroF1: f1N > 0 ? f1Sum / f1N : null,
    unclassifiedRate: points > 0 ? unclassified / points : 0,
    falseBuildingRate: notBuilding > 0 ? falseBuilding / notBuilding : null,
    lowNoiseCalledGround,
    lowNoisePoints,
  };
}
