#!/usr/bin/env node
/**
 * solve-lock.mjs — regenerate conda-linux-64.lock and the conda half of
 * oracle-pins.json from the conda-forge index.
 *
 * The Dockerfile installs from the lock, never from the version specs below.
 * A spec such as `gdal=3.13.1` still leaves a build string, a Python ABI and
 * two hundred transitive libraries free, and those decide output bytes as
 * surely as the version does. Solving once and committing the result is what
 * makes the image the same image next year.
 *
 * The solve runs on the HOST and produces a lock for linux-64. That is
 * deliberate: it needs no container runtime, so the lock can be reviewed and
 * regenerated on a machine that has no daemon, and the version pins can be
 * checked against the validation corpus before anything is built.
 *
 * CONDA_OVERRIDE_GLIBC and CONDA_OVERRIDE_LINUX are passed because the solver
 * otherwise reads the virtual packages of the host it runs on, and a macOS host
 * reports no glibc at all, which makes every linux-64 package uninstallable.
 * The values are the base image's, not this machine's; they are recorded in the
 * lock header so a later reader can see which floor the solve assumed.
 *
 * Usage:  node validation/oracles/solve-lock.mjs [--check]
 *   --check re-solves and fails if the result differs from the committed lock,
 *           which is how CI notices that conda-forge has moved.
 */

import { spawnSync } from 'node:child_process';
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = resolve(dirname(fileURLToPath(import.meta.url)));
const LOCK = resolve(HERE, 'conda-linux-64.lock');
const PINS = resolve(HERE, 'oracle-pins.json');

/** The solve platform. PDAL has no conda-forge build for linux-aarch64 above
 *  2.7.2, so the version this corpus cites, 2.10.2, exists only for linux-64.
 *  That single fact decides the architecture of the whole image. */
export const PLATFORM = 'linux-64';

/** The base image's glibc and kernel, not this machine's. */
export const VIRTUAL = { glibc: '2.41', linux: '6.12' };

/**
 * The specs. Every one is exact, including the ones that look redundant.
 *
 * `python` fixes the ABI that gdal, laspy, lazrs and whitebox_tools are all
 * built against, so leaving it free would let a rebuild silently move five
 * packages at once.
 *
 * `whitebox_tools` is the compiled binary, built from source by conda-forge and
 * therefore checksummed in this lock. The `whitebox` Python wrapper does NOT
 * ship it: on first import it fetches
 * https://www.whiteboxgeo.com/WBT_Linux/WhiteboxTools_linux_amd64.zip, a URL
 * that carries no version and no checksum, and it verifies no hash. Installing
 * the conda package and pointing WBT_PATH at it is what stops that fetch.
 *
 * `nodejs` is 22 because 3d-tiles-validator@0.6.1 pulls better-sqlite3, which
 * has no prebuilt binary for Node 26 and fails its native build.
 */
export const SPECS = [
  'python=3.12.14',
  'pdal=2.10.2',
  'gdal=3.13.1',
  'whitebox=2.3.6',
  'whitebox_tools=2.4.0',
  'laspy=2.7.0',
  'lazrs-python=0.8.2',
  'nodejs=22.23.2',
  'pip',
];

/** Which solved package supplies each oracle the validation records name. */
const ORACLE_PACKAGES = { GDAL: 'libgdal-core', PDAL: 'pdal' };

function solve() {
  const args = [
    'create', '--yes', '--dry-run', '--json',
    '--platform', PLATFORM,
    '-c', 'conda-forge',
    '-n', 'olv-oracles',
    ...SPECS,
  ];
  const r = spawnSync('micromamba', args, {
    encoding: 'utf8',
    maxBuffer: 64 * 1024 * 1024,
    env: {
      ...process.env,
      CONDA_OVERRIDE_GLIBC: VIRTUAL.glibc,
      CONDA_OVERRIDE_LINUX: VIRTUAL.linux,
    },
  });
  if (r.error) {
    throw new Error(`micromamba could not be run: ${r.error.message}`);
  }
  let doc;
  try {
    doc = JSON.parse(r.stdout);
  } catch {
    throw new Error(`micromamba printed no JSON (exit ${r.status}):\n${r.stderr}`);
  }
  if (!doc.success) {
    const errs = (doc.log_history ?? []).filter((e) => e.level === 'error').map((e) => e.message);
    throw new Error(`the solve failed:\n${errs.join('\n')}`);
  }
  // Sorted by name so the lock is a reviewable diff rather than solver order.
  return [...doc.actions.LINK].sort((a, b) => a.name.localeCompare(b.name));
}

function renderLock(pkgs) {
  const total = pkgs.reduce((a, p) => a + p.size, 0);
  return (
    [
      '# conda-linux-64.lock — the exact package set validation/oracles/Dockerfile installs.',
      '#',
      '# Generated by validation/oracles/solve-lock.mjs. Do not edit by hand: the',
      '# hashes are what make the install verifiable, and a hand-edited line is a',
      '# hash nobody computed.',
      '#',
      `# platform: ${PLATFORM}`,
      `# solved against virtual packages __glibc=${VIRTUAL.glibc} __linux=${VIRTUAL.linux}`,
      `# specs: ${SPECS.join(' ')}`,
      `# ${pkgs.length} packages, ${(total / 1e6).toFixed(1)} MB of downloads`,
      '@EXPLICIT',
    ].join('\n') +
    '\n' +
    pkgs.map((p) => `${p.url}#${p.sha256}`).join('\n') +
    '\n'
  );
}

function main() {
  const check = process.argv.includes('--check');
  const pkgs = solve();
  const lock = renderLock(pkgs);

  const oracleVersions = {};
  for (const [oracle, pkgName] of Object.entries(ORACLE_PACKAGES)) {
    const p = pkgs.find((x) => x.name === pkgName);
    if (p) oracleVersions[oracle] = p.version;
  }

  // The named packages get an entry of their own in the pin manifest. The other
  // two hundred are in the lock with their hashes; repeating them here would be
  // a second copy to keep in step with the first.
  const named = new Set([
    ...SPECS.map((s) => s.split('=')[0]),
    ...Object.values(ORACLE_PACKAGES),
    'libpdal',
    'proj',
  ]);
  const pinned = {};
  for (const p of pkgs) {
    if (!named.has(p.name)) continue;
    pinned[p.name] = {
      version: p.version,
      build: p.build_string,
      url: p.url,
      sha256: p.sha256,
      sizeBytes: p.size,
    };
  }

  if (check) {
    if (!existsSync(LOCK)) {
      console.error('conda-linux-64.lock is missing; run this script without --check.');
      process.exit(1);
    }
    const committed = readFileSync(LOCK, 'utf8');
    if (committed !== lock) {
      console.error(
        'validation/oracles: the committed lock is not what conda-forge solves to today.\n' +
          'This is expected when a package is rebuilt upstream. Regenerate the lock, rebuild\n' +
          'the image, and check every version the validation records cite before committing.',
      );
      process.exit(1);
    }
    console.log(`validation/oracles: the lock still solves identically (${pkgs.length} packages).`);
    return;
  }

  writeFileSync(LOCK, lock, 'utf8');
  const existing = existsSync(PINS) ? JSON.parse(readFileSync(PINS, 'utf8')) : {};
  const next = {
    ...existing,
    generatedBy: 'validation/oracles/solve-lock.mjs',
    platform: PLATFORM,
    virtualPackages: VIRTUAL,
    condaSpecs: SPECS,
    condaPackageCount: pkgs.length,
    condaDownloadBytes: pkgs.reduce((a, p) => a + p.size, 0),
    oracleVersions: { ...(existing.oracleVersions ?? {}), ...oracleVersions },
    condaPinned: pinned,
  };
  writeFileSync(PINS, JSON.stringify(next, null, 2) + '\n', 'utf8');
  console.log(
    `wrote conda-linux-64.lock (${pkgs.length} packages, ` +
      `${(next.condaDownloadBytes / 1e6).toFixed(1)} MB) and updated oracle-pins.json`,
  );
  for (const [k, v] of Object.entries(oracleVersions)) console.log(`  ${k} ${v}`);
}

if (process.argv[1] && resolve(process.argv[1]) === resolve(fileURLToPath(import.meta.url))) {
  main();
}
