/**
 * hygienePatterns.mjs — shared high-confidence patterns for the shipped-file
 * hygiene scan (used by lint-archive-vocab.mjs; unit-tested directly).
 *
 * Two families:
 *   SECRET — credential shapes that must never reach a shipped file: private-key
 *     headers, cloud/provider access keys and tokens, and a `client_secret`
 *     with a real value. Deliberately shape-specific so a package-lock integrity
 *     hash, embedded base64/WASM, or the word "token" in prose does NOT trip.
 *   NARRATION — conversational/process artifacts (an assistant talking about the
 *     conversation) that have no place in a shipped file.
 *   MARKUP — tool-call / assistant transcript tags. A README reached the citable
 *     archive ending in two stray closing tags from a tool call. Nothing caught
 *     it: NARRATION matches prose, and the PR hygiene scan reads a diff, so a
 *     tag committed once is never re-examined. Matched as a whole trimmed line
 *     or an opening tag, and only for that tag vocabulary, so real markup in an
 *     HTML, SVG or XML fixture cannot trip it.
 *   ROADMAP — a promise about a release that has not happened. Distinct from a
 *     SCOPE statement ("ordered verification is future work"), which is
 *     load-bearing and stays legal; only forms that commit the project to
 *     unbuilt work, or that date themselves to an authoring session.
 *
 * Pure and dependency-free so both the gate and its negative-control test share
 * one definition. Kept narrow on purpose: the audit's anti-goal is a scan that
 * cries wolf on high-entropy strings that are legitimately present.
 */

/** Credential shapes. Each carries a short label for the failure message. */
export const SECRET_PATTERNS = [
  { label: 'private-key header', re: /-----BEGIN (?:[A-Z0-9]+ )*PRIVATE KEY-----/ },
  { label: 'AWS access key id', re: /\bAKIA[0-9A-Z]{16}\b/ },
  { label: 'GitHub personal access token', re: /\bghp_[A-Za-z0-9]{36}\b/ },
  { label: 'GitHub fine-grained token', re: /\bgithub_pat_[A-Za-z0-9_]{40,}\b/ },
  { label: 'OpenAI-style secret key', re: /\bsk-[A-Za-z0-9]{32,}\b/ },
  { label: 'Slack token', re: /\bxox[baprs]-[A-Za-z0-9-]{12,}\b/ },
  { label: 'client_secret value', re: /client_secret["'\s:=]{1,4}[A-Za-z0-9_\-]{20,}/i },
];

/**
 * Conversational / process-narration phrases (case-insensitive). Kept to
 * UNAMBIGUOUS assistant-voice tells: broad forms like "the user asked" are
 * deliberately excluded because they legitimately describe user intent in UI
 * code ("the size the user asked for").
 */
export const NARRATION_PATTERNS = [
  /\bas an AI\b/i,
  /\bgenerated by (?:claude|chatgpt|gpt|an ai)\b/i,
  /\bhere is the prompt\b/i,
  /\bthinking aloud\b/i,
  /\bthe user asked me to\b/i,
];

/** Tag names that belong to a tool-call transcript and to nothing else. */
const TOOL_TAGS = '(?:antml:)?(?:invoke|function_calls|function_results|parameter|thinking)';

export const MARKUP_PATTERNS = [
  new RegExp('^\\s*</' + TOOL_TAGS + '>\\s*$', 'i'),
  new RegExp('<' + TOOL_TAGS + '(?:\\s+\\w+=|>)', 'i'),
];

export const ROADMAP_PATTERNS = [
  /\bin a (?:later|future) (?:release|version|session)\b/i,
  /\b(?:planned|scheduled) for a (?:later|future) (?:release|version|session)\b/i,
  /\ba follow-up cut\b/i,
  /\bwe should eventually\b/i,
];

/** The first tool-call markup shape that matches `line`, or null. */
export function findMarkup(line) {
  for (const re of MARKUP_PATTERNS) {
    const m = line.match(re);
    if (m) return m[0].trim();
  }
  return null;
}

/** The first roadmap promise that matches `line`, or null. */
export function findRoadmapPromise(line) {
  for (const re of ROADMAP_PATTERNS) {
    const m = line.match(re);
    if (m) return m[0];
  }
  return null;
}

/** The first secret pattern that matches `line`, or null. */
export function findSecret(line) {
  for (const p of SECRET_PATTERNS) if (p.re.test(line)) return p.label;
  return null;
}

/** The first narration phrase that matches `line`, or null. */
export function findNarration(line) {
  for (const re of NARRATION_PATTERNS) {
    const m = line.match(re);
    if (m) return m[0];
  }
  return null;
}
