/**
 * exporters.ts
 *
 * Serialise a `PointCloud` back out to common point-cloud formats: XYZ, CSV,
 * PLY (ASCII) and OBJ. Pure functions — no DOM, no three.js — so they are
 * straightforward to unit-test; the UI layer handles turning the result into
 * a download.
 *
 * Coordinates are written in **global** space (the cloud's local positions
 * plus its `origin`), so an exported file carries real-world survey
 * coordinates and round-trips cleanly back through the importer.
 */

import type { PointCloud } from '../model/PointCloud';

/** The export formats this module produces. */
export type ExportFormat = 'xyz' | 'csv' | 'ply' | 'obj';

/** Format a coordinate to millimetre precision without exponent notation. */
function coord(v: number): string {
  return v.toFixed(3);
}

/**
 * Horizontal-coordinate formatter for XYZ/CSV (v0.4.5, workplan C5).
 * Projected/local frames keep the millimetre 3 dp; a GEOGRAPHIC CRS gets
 * 7 dp, because 3 dp of a degree is ~110 m of position — the old fixed
 * precision silently destroyed lat/lon exports. 1e-7° ≈ 1.1 cm at the
 * equator, matching the survey convention for degree output. Z stays 3 dp
 * in both cases (heights are linear units even in a geographic CRS).
 */
function horizontalCoordFormatter(cloud: PointCloud): (v: number) => string {
  return cloud.metadata?.crs?.isGeographic === true ? (v) => v.toFixed(7) : coord;
}

/**
 * Serialise to plain-text XYZ (or CSV when `delimiter` is `,`).
 * Columns: `x y z`, then — each only when the cloud carries the channel —
 * `r g b` (0–255), `intensity` (raw 16-bit) and `classification` (raw
 * ASPRS code). A CSV always gets a header row naming the columns; an XYZ
 * gets a `# columns: …` comment line only when the optional intensity /
 * classification columns are present (so a plain x-y-z file stays
 * byte-identical to earlier releases, and the extra columns are never a
 * guessing game for the next tool). Importers — ours included — skip
 * `#` comment lines by long-standing XYZ convention.
 */
export function toXyz(cloud: PointCloud, delimiter = ' '): string {
  const { positions, colors, origin } = cloud;
  const n = cloud.pointCount;
  const lines: string[] = [];
  const csv = delimiter === ',';
  const hcoord = horizontalCoordFormatter(cloud);
  // Length guards: a malformed cloud with a misaligned channel drops the
  // column rather than writing values from the wrong points.
  const intensity =
    cloud.intensity && cloud.intensity.length === n ? cloud.intensity : undefined;
  const classification =
    cloud.classification && cloud.classification.length === n
      ? cloud.classification
      : undefined;
  const columns = [
    'x',
    'y',
    'z',
    ...(colors ? ['r', 'g', 'b'] : []),
    ...(intensity ? ['intensity'] : []),
    ...(classification ? ['classification'] : []),
  ];
  if (csv) lines.push(columns.join(','));
  else if (intensity || classification) lines.push(`# columns: ${columns.join(' ')}`);

  for (let i = 0; i < n; i++) {
    const row: Array<string | number> = [
      hcoord(positions[i * 3] + origin[0]),
      hcoord(positions[i * 3 + 1] + origin[1]),
      coord(positions[i * 3 + 2] + origin[2]),
    ];
    if (colors) row.push(colors[i * 3], colors[i * 3 + 1], colors[i * 3 + 2]);
    if (intensity) row.push(intensity[i]);
    if (classification) row.push(classification[i]);
    lines.push(row.join(delimiter));
  }
  return lines.join('\n') + '\n';
}

/** Serialise to CSV — comma-delimited XYZ with a header row. */
export function toCsv(cloud: PointCloud): string {
  return toXyz(cloud, ',');
}

/** Serialise to ASCII PLY, with `uchar` RGB when the cloud carries colour. */
export function toPly(cloud: PointCloud): string {
  const { positions, colors, origin } = cloud;
  const n = cloud.pointCount;

  const header = [
    'ply',
    'format ascii 1.0',
    'comment Generated by OpenLiDARViewer',
    `element vertex ${n}`,
    'property float x',
    'property float y',
    'property float z',
  ];
  if (colors) {
    header.push('property uchar red', 'property uchar green', 'property uchar blue');
  }
  header.push('end_header');

  const lines: string[] = [header.join('\n')];
  for (let i = 0; i < n; i++) {
    const x = coord(positions[i * 3] + origin[0]);
    const y = coord(positions[i * 3 + 1] + origin[1]);
    const z = coord(positions[i * 3 + 2] + origin[2]);
    if (colors) {
      lines.push(`${x} ${y} ${z} ${colors[i * 3]} ${colors[i * 3 + 1]} ${colors[i * 3 + 2]}`);
    } else {
      lines.push(`${x} ${y} ${z}`);
    }
  }
  return lines.join('\n') + '\n';
}

/**
 * Serialise to OBJ as a vertex-only cloud. Colour, when present, is written
 * with the widely-supported `v x y z r g b` extension (channels in 0–1).
 */
export function toObj(cloud: PointCloud): string {
  const { positions, colors, origin } = cloud;
  const n = cloud.pointCount;

  const lines: string[] = [
    '# OpenLiDARViewer point-cloud export',
    `# ${n} points`,
  ];
  for (let i = 0; i < n; i++) {
    const x = coord(positions[i * 3] + origin[0]);
    const y = coord(positions[i * 3 + 1] + origin[1]);
    const z = coord(positions[i * 3 + 2] + origin[2]);
    if (colors) {
      const r = (colors[i * 3] / 255).toFixed(4);
      const g = (colors[i * 3 + 1] / 255).toFixed(4);
      const b = (colors[i * 3 + 2] / 255).toFixed(4);
      lines.push(`v ${x} ${y} ${z} ${r} ${g} ${b}`);
    } else {
      lines.push(`v ${x} ${y} ${z}`);
    }
  }
  return lines.join('\n') + '\n';
}

/** Serialise `cloud` to `format`. */
export function exportCloud(cloud: PointCloud, format: ExportFormat): string {
  switch (format) {
    case 'xyz': return toXyz(cloud);
    case 'csv': return toCsv(cloud);
    case 'ply': return toPly(cloud);
    case 'obj': return toObj(cloud);
    default: {
      const exhaustive: never = format;
      throw new Error(`Unknown export format: ${String(exhaustive)}`);
    }
  }
}
