/**
 * exporters.ts
 *
 * Serialise a `PointCloud` back out to common point-cloud formats: XYZ, CSV,
 * PLY (ASCII) and OBJ. Pure functions — no DOM, no three.js — so they are
 * straightforward to unit-test; the UI layer handles turning the result into
 * a download.
 *
 * Coordinates are written in **global** space (the cloud's local positions
 * plus its `origin`), so an exported file carries real-world survey
 * coordinates and round-trips cleanly back through the importer.
 */

import type { PointCloud } from '../model/PointCloud';

/** The export formats this module produces. */
export type ExportFormat = 'xyz' | 'csv' | 'ply' | 'obj';

/** Format a coordinate to millimetre precision without exponent notation. */
function coord(v: number): string {
  return v.toFixed(3);
}

/**
 * Serialise to plain-text XYZ (or CSV when `delimiter` is `,`).
 * Columns: `x y z` and, when the cloud has colour, `r g b` in 0–255.
 * A CSV gets a header row.
 */
export function toXyz(cloud: PointCloud, delimiter = ' '): string {
  const { positions, colors, origin } = cloud;
  const n = cloud.pointCount;
  const lines: string[] = [];
  const csv = delimiter === ',';
  if (csv) lines.push(colors ? 'x,y,z,r,g,b' : 'x,y,z');

  for (let i = 0; i < n; i++) {
    const x = coord(positions[i * 3] + origin[0]);
    const y = coord(positions[i * 3 + 1] + origin[1]);
    const z = coord(positions[i * 3 + 2] + origin[2]);
    if (colors) {
      lines.push([x, y, z, colors[i * 3], colors[i * 3 + 1], colors[i * 3 + 2]].join(delimiter));
    } else {
      lines.push([x, y, z].join(delimiter));
    }
  }
  return lines.join('\n') + '\n';
}

/** Serialise to CSV — comma-delimited XYZ with a header row. */
export function toCsv(cloud: PointCloud): string {
  return toXyz(cloud, ',');
}

/** Serialise to ASCII PLY, with `uchar` RGB when the cloud carries colour. */
export function toPly(cloud: PointCloud): string {
  const { positions, colors, origin } = cloud;
  const n = cloud.pointCount;

  const header = [
    'ply',
    'format ascii 1.0',
    'comment Generated by OpenLiDARViewer',
    `element vertex ${n}`,
    'property float x',
    'property float y',
    'property float z',
  ];
  if (colors) {
    header.push('property uchar red', 'property uchar green', 'property uchar blue');
  }
  header.push('end_header');

  const lines: string[] = [header.join('\n')];
  for (let i = 0; i < n; i++) {
    const x = coord(positions[i * 3] + origin[0]);
    const y = coord(positions[i * 3 + 1] + origin[1]);
    const z = coord(positions[i * 3 + 2] + origin[2]);
    if (colors) {
      lines.push(`${x} ${y} ${z} ${colors[i * 3]} ${colors[i * 3 + 1]} ${colors[i * 3 + 2]}`);
    } else {
      lines.push(`${x} ${y} ${z}`);
    }
  }
  return lines.join('\n') + '\n';
}

/**
 * Serialise to OBJ as a vertex-only cloud. Colour, when present, is written
 * with the widely-supported `v x y z r g b` extension (channels in 0–1).
 */
export function toObj(cloud: PointCloud): string {
  const { positions, colors, origin } = cloud;
  const n = cloud.pointCount;

  const lines: string[] = [
    '# OpenLiDARViewer point-cloud export',
    `# ${n} points`,
  ];
  for (let i = 0; i < n; i++) {
    const x = coord(positions[i * 3] + origin[0]);
    const y = coord(positions[i * 3 + 1] + origin[1]);
    const z = coord(positions[i * 3 + 2] + origin[2]);
    if (colors) {
      const r = (colors[i * 3] / 255).toFixed(4);
      const g = (colors[i * 3 + 1] / 255).toFixed(4);
      const b = (colors[i * 3 + 2] / 255).toFixed(4);
      lines.push(`v ${x} ${y} ${z} ${r} ${g} ${b}`);
    } else {
      lines.push(`v ${x} ${y} ${z}`);
    }
  }
  return lines.join('\n') + '\n';
}

/** Serialise `cloud` to `format`. */
export function exportCloud(cloud: PointCloud, format: ExportFormat): string {
  switch (format) {
    case 'xyz': return toXyz(cloud);
    case 'csv': return toCsv(cloud);
    case 'ply': return toPly(cloud);
    case 'obj': return toObj(cloud);
    default: {
      const exhaustive: never = format;
      throw new Error(`Unknown export format: ${String(exhaustive)}`);
    }
  }
}
